### ISSUE TITLE
It would be nice to use the standard linux 'df' command

### ISSUE THREAD

**Issue by dswartz** [parodyne/esos#162]
Apparently we are running a busybox version, which does not have the same command line options.  This breaks at least one application (veeam backup and recovery - which can use several different types of repositories.  One of which is 'a linux repository'.  Veeam B&R ssh's in to the linux server and runs some flavor of 'df' to determine how much space is available.  This fails due to the busybox 'df' command not supporting the requisite command line options :(

**Comment by msmith626** [comment]
Yeah, its kind of getting annoying using Busybox... will probably phase it
out someday and use the real packages. We've already had to do this for
many other programs. Do you happen to know which package "df" comes from?

--Marc

**Comment by dswartz** [comment]
Dunno why I didn't see your reply.  Sigh.  Anyway, on centos 6.6, it is the coreutils package...

**Comment by msmith626** [comment]
No problem... I'm heavily considering adding coreutils and util-linux
(well, util-linux is already in build, but we only use a few parts of it).
Trying to think of what else we would use by taking Busybox out of root
(would stay for initramfs). I know GNU sed, vi/vim, and maybe some other
user friendly text editor (nano). What's the easy to use text editor in
Linux these days?

--Marc

**Comment by dswartz** [comment]
I like emacs (the nox) flavor, but I'm not sure how heavyweight that would be?  The real 'ed' command, not the busybox version (just different enough to be annoying...)

**Comment by msmith626** [comment]
Did you find a work-around for the 'df' tool? I recently looked at pulling out Busybox, and after looking at all the commands it provides, and the additional packages required to get the same functionality, I've decided not to pursue this. As we already do for other tools/utilities, if the Busybox variant isn't what we want, then we can just install the single tool and disable it in Busybox.

--Marc

**Comment by dswartz** [comment]
On 2016-05-26 14:27, Marc A. Smith wrote:
> Did you find a work-around for the 'df' tool? I recently looked at
> pulling out Busybox, and after looking at all the commands it
> provides, and the additional packages required to get the same
> functionality, I've decided not to pursue this. As we already do for
> other tools/utilities, if the Busybox variant isn't what we want, then
> we can just install the single tool and disable it in Busybox.

Not really.  I only needed it for veeam to treat a linux host as a 
repository.  It uses 'df' to determine how much space is available.  
Because of the incompatible argument, it chokes, so I used a different 
repository type...

**Comment by msmith626** [comment]
Okay, thanks. And if there are any other utilities that are really impacting, we can do the work-around as I described.

--Marc

**Comment by dswartz** [comment]
Sorry to be a PITA, but could you re-open this?  I had been using an OmniOS VM as my backup storage server, but I moved off that (e.g. both servers are now running esos+zfs), so I'm back in the boat of not being able to use the busybox 'df' command...

**Comment by msmith626** [comment]
This has been completed (master).
