### ISSUE TITLE
Unable to build stable/master on Ubuntu 12.04

### ISSUE THREAD

**Issue by stuarthopkins** [parodyne/esos#164]
I attempted to build both the stable/master builds on a clean Ubuntu 12.04.5 system using the documented instructions however both builds failed. Initially the builds failed due to a missing package gtk-doc-tools (which isn't mentioned as a requirement). I tried again (both stable and master) and hit a different failure this time, due to libqb not being installed. This package isn't found in the standard ubuntu repositories (including universe/multiverse) and from looking at http://packages.ubuntu.com/trusty/libqb0 it would appear that it only becomes available in the trusty release (14.04 LTS).

I'm going to build a clean 14.04 LTS system now, but can someone confirm if 12.04 is no longer supported as a build platform.

Logfile snippet below (original logs are too large to upload)

/tmp/esos-master/esos/work/build/pacemaker-1.1.12/pengine/pengine metadata > pengine.xml
/tmp/esos-master/esos/work/build/pacemaker-1.1.12/pengine/.libs/lt-pengine: error while loading shared libraries: libqb.so.0: cannot open shared object file: No such file or directory
make[3]: *** [pengine.xml] Error 127
rm pengine.xml
make[3]: Leaving directory `/tmp/esos-master/esos/work/build/pacemaker-1.1.12/pengine'
make[2]: *** [core] Error 1
make[2]: Leaving directory `/tmp/esos-master/esos/work/build/pacemaker-1.1.12'
make[1]: *** [pacemaker] Error 2
make[1]: Leaving directory `/tmp/esos-master/esos'
make: *** [all] Error 2

**Comment by stuarthopkins** [comment]
Marc, I will give the build a go on RHEL7.1 shortly. FWIW, I just tried with a clean Ubuntu 14.04 system and that failed as well. I'm redoing the build with -j1 so the logs actually make sense and I can find the root-cause.

**Comment by dswartz** [comment]
ubuntu 14.04 works for me, except for the opensm package which i don't use, so i was just doing 'make -i' :)

**Comment by msmith626** [comment]
Is this safe to close now?

**Comment by stuarthopkins** [comment]
I wouldn't say its safe to close as without the -i option you can't do a standard build using the documented instructions. I'd like to take a look at why opensm wont build (I've seen the same error). If using the -i option is documented as the only supported approach then fair enough. This would obviously include the change in the docs from 12.04 to 14.04 (needed for libqb).

**Comment by dswartz** [comment]
Yeah, the opensm thing would be an issue for me if I was running standard infiniband.  My IB cards run in 10/40 gbe ethernet mode, so I don't care.  Still, my OCD objects to having to do things like '-i' :)

**Comment by flasharray** [comment]
Hi! Marc A. Smith
thanks  quick reply. 

> stock kernel OFED that ESOS supports ? 
  bellow still error stock kernel 3.x /4.x    (auto build / manual build) 

http://download.esos-project.com/dist_files/
scst-3.0.x_r6474.tar.gz                            14-Aug-2015 09:39      7M
scst-trunk_r5816.tar.gz                            20-Oct-2014 13:25      7M
scst-trunk_r5854.tar.gz                            11-Nov-2014 09:17      7M
scst-trunk_r6146.tar.gz                            23-Mar-2015 15:32      7M
scst-trunk_r6566.tar.gz                            29-Oct-2015 12:44      7M    (error) esos last version 

linux-3.14.19.tar.xz                               20-Oct-2014 13:25     75M    (error) + scst-trunk_r6566.tar.gz
linux-3.14.36.tar.xz                               25-Mar-2015 09:41     75M
linux-4.1.11.tar.xz                                23-Oct-2015 13:42     79M   (error)  esos last version 

How to skip scst ofa_kernel refrence in esos make script  ?

**Comment by msmith626** [comment]
I added the fix for this last night (cf55fc1a47a1cbbe1b375435b8baa7477deb5794) and tested today. I used an Amazon EC2 instance: Ubuntu Server 14.04 LTS

I logged in and su'd to root, then ran this:
apt-get update
apt-get install build-essential
apt-get install git autoconf gawk flex bison gcc-multilib unzip libtinfo-dev libtool lsscsi kpartx libxslt1-dev groff gettext xsltproc pkg-config autopoint zip

Then, as a normal ("ubuntu") user, I ran this:
git clone https://github.com/parodyne/esos.git
cd esos
auotconf
./configure --enable-zfs
make -j4
sudo make image
make pkg_dist

The build completed successfully, so I will now consider this issue resolved.

--Marc

**Comment by dswartz** [comment]
Build worked fine.  Testing later...

**Comment by dswartz** [comment]
Everything worked like a champ!  The only thing I am not sure about is 
that the zvol device (zd0) was presented as a block device, so I used 
it.  I seem to recall you can get different zdN devices, and end up with 
symlinks pointing to the relevant one.  e.g. I could swear I once got 
the wrong zdN device and got hosed, whereas manually creating the scst 
device using /dev/zvol/pool/zvolname (or whatever) works properly.  Just 
something to consider...

**Comment by dswartz** [comment]
Spoke too quickly.  Rebooted, and no scst device?  Looked at 'zpool 
status' and ... no pools???  ran 'zpool import test' and it was there.  
Looked at /var/log/boot and saw:

Thu Jun  2 11:43:26 2016: Loading ZFS...
Thu Jun  2 11:43:26 2016: Starting the ZFS Event Daemon...
Thu Jun  2 11:43:26 2016: Importing ZFS pools...
Thu Jun  2 11:43:26 2016: no pools available to import

Maybe this is running too soon in the game?

**Comment by msmith626** [comment]
You tell me -- why does it say "no pools available to import"? I'm not the
ZFS expert here. =)

As for the Ubuntu build issue, it sounds like that is resolved.
