### ISSUE TITLE
3-node active-backup ESOS cluster

### ISSUE THREAD

**Issue by defender52** [parodyne/esos#165]
Hello Mark,
I'm trying to build 3-node active-backup ESOS cluster:
storage1 - active (IDE HDDs 7200);
storage2 - backup for storage1 (drbd protocol C);
                 backup for storage3 (drbd protocol B);
storage3 - active (SSD HDDs);

Objective: failure protection for both storage1 and storage3;

Estimated scheme:
2 ms_scst ALUA-supported crm resources for different ALUA device groups.

My question:
1. Is this scheme possible?
2. Have you ever implemented such a scheme? If yes, what are the possible problems and workarounds, or even maybe how-to I haven't found?

Best regards,
Alexander

PS I've already tried it but faced problems with 2 ALUA device groups startup/promoting on storage2.

**Comment by msmith626** [comment]
Hi Alexander,

So, you'd be doing stacked DRBD resources for this setup? Obviously this is
possible using DRBD, but as you mentioned, the SCST resource agent (RA)
only supports 2 nodes. I don't have a way around this at the moment -- when
designing the RA, limiting it to 2 nodes made sense.

In my honest opinion, the setup you described seems very complex, and in my
experience, more complexity equals a less stable solution / more problems.

Is there a specific reason you want to use three nodes? I would recommend
just going with a 2-node DRBD setup if you're looking for resiliency.

I would like to support a > 2 node setup, especially with the DRBD 9 stuff,
but I'm not ready to put the resources into developing that at the moment.


--Marc

**Comment by dswartz** [comment]
Is the 3rd node just a belts and suspenders backup?  If it is protocol B, that is my guess.  If you were using ZFS, you could use 'zfs send' and 'zfs receive' to send incremental snaps from storage2 -> storage3.

**Comment by defender52** [comment]
Hi Marc, thanks for reply.
Sorry to read that - the idea was to have 2 stacked active iscsi-storages but with 3 phisical servers except 4 (1 IDE (storage1), 1 SSD (stirage 3) and 1 common replica for both (storage2). SSD and IDE storages (storage1 and 3) contain different data. IDE is designed for file shares and SSD for fast VM VHDs.
So I tried to run scst on every storage and it starts fine but only for 1 alua device group on each server (and I believed that it could run for 2 alua device groups on common storage 2). 
Your guess about DRBD proper functionality in 3-node stack is right - it works fine.

2-node stack's been working in production without any issue for more than 2 years and keeps working further, thanks to your work. It's built on Supermicro components, Adaptec raid controllers and SFP+ network adatpers and commutators. I'm really happy with such a project as ESOS and dare to hope for its further development and functionality extension.

Rgds
Alexander

**Comment by defender52** [comment]
Dear dswartz,
No, storage #2 is not a backup, but in DRBD stack with #1 and #2 and replicates fine. It was planned to be a reserved iscsi target in case of #1 or #3 HW failure.

Rgds
Alexander

**Comment by msmith626** [comment]
I'd like to support this... a > 2 node cluster. Is the main hang up right
now the ESOS SCST RA (resource agent)?

--Marc

**Comment by defender52** [comment]
I'm glad to hear that and ready to contribute my time and efforts to it.
Yes, since DRBD 3-node stack works perfectly.

Rgds
Alexander

**Comment by feldsam** [comment]
I think that SCST RA need complete rewrite  resp. we need some program for manage scst and alua states.

**Comment by msmith626** [comment]
Yes, I agree Kristian. The current RA is not designed to handle this. At
first thought DLM comes to mind as a communication means, but maybe not.

--Marc

**Comment by feldsam** [comment]
hmm, with dlm/clvm I have problems also on stable centos 7....I don't like it :)

**Comment by feldsam** [comment]
I think that proposed API should handle this

**Comment by msmith626** [comment]
Okay, we'll see what we can do, when we get there.

Alexander: We don't have a solution today, but hopefully in the next month
or two may have an option.


--Marc

**Comment by defender52** [comment]
Great, I'm looking forward for it, thanks.
Rgds
Alexander

**Comment by defender52** [comment]
DC,
Is there any news about the issue?
Is there any possibility to solve this?

Rgds
Alexander

**Comment by msmith626** [comment]
No, sorry, I don't have an update on this. I do agree with Kristian that to
do this, the current SCST RA would need a complete re-write. This request
is a long-term goal for ESOS, but unfortunately not anything that will be
addressed in the near future. Until then we are stuck with the dual-head
model for ESOS clusters.

--Marc

**Comment by defender52** [comment]
I see, thank you.
Anyway I'm looking forward for this update and always ready to participate in testing.
Rgds
Alexander

**Comment by feldsam** [comment]
Hi Mark, what about Esos API? I wanna write my own, but I was need nodejs support ;) Probably I can use SSH for executing and monitoring hosts...

**Comment by msmith626** [comment]
The API being developed for ESOS would not be a fit for this use case. I'd
do it with SSH or some other means (something like DLM sounds like a good
fit, but maybe not). Using SSH sounds like it would add a lot of
complexity, but maybe not. Whatever you decide is good with me.

--Marc

**Comment by msmith626** [comment]
Hi,

Another user has created some new SCST RA's -- these function a little differently, in that most of the SCST configuration is performed from the RA itself, and one is specifically for Fibre Channel.

At least one of these new RA's supports a node count > 2; special thanks to @FZachlod for creating these. The RA's are in ESOS (ocf:onesty:scst_aluadg and ocf:onesty:scst_qla2xtgt) and the project page for those is here: https://github.com/FZachlod/scst_ocf_ra

Felix is on the esos-users mailing list, so you can get support for these their, or by using his project's issues page above.

I'm going to close this issue here, and if there is usage/support questions for the new RA, see the above message.

--Marc
