### ISSUE TITLE
Compile LVM with lvmlockd support

### ISSUE THREAD

**Issue by feldsam** [parodyne/esos#175]
Hi Marc, I found lvmlockd https://www.mankier.com/8/lvmlockd and it looks very good. I personaly tested it on two centos 7 nodes and it's working fine. It use sanlock or dlm for store locks. It has advantages over clvm, like thin volumes and snapshots, easier configuration..... Volumes can be activated exclusively or in shared mode (-aey, -asy)

I think, that simplicity and thin volumes availabilty is big benefit over traditional clvm.

Thank you.

---
I personaly hate clvm :), on esos working fine after debuging fencing (you remember), but on compute nodes it is horible

**Comment by msmith626** [comment]
Is it ready for production use? From what I understand, lvmlockd is
intended to be the successor to CLVM, but last I knew it wasn't ready yet.

--Marc

**Comment by feldsam** [comment]
I decide that it is, when it is in centos 7 repo and lvm config.

**Comment by msmith626** [comment]
What version of LVM2 is it on? I looked and we're not explicitly disabling
it in ESOS, so maybe its default in a newer version of LVM2.

(I'm all for this, was just waiting for it to be ready.)

**Comment by feldsam** [comment]
Here is version of rpm package

Name        : lvm2-lockd
Arch        : x86_64
Epoch       : 7
Version     : 2.02.130
Release     : 5.el7_2.1
Size        : 165 k
Repo        : installed
From repo   : updates
Summary     : LVM locking daemon
URL         : http://sources.redhat.com/lvm2
License     : GPLv2
Description : 
            : LVM commands use lvmlockd to coordinate access to shared storage.

Name        : lvm2
Arch        : x86_64
Epoch       : 7
Version     : 2.02.130
Release     : 5.el7_2.1
Size        : 2.1 M
Repo        : installed
From repo   : updates
Summary     : Userland logical volume management tools

S pozdravom / Best regards Feldsam
Tel.: +420 773 303 353

www.feldsam.cz - webdesign, webdeveloping, webhosting

http://navolnenoze.cz/prezentace/kristian-feldsam/

Address: Praha 1 - Nove Mesto, Petrske namesti 1186/1, ZIP 110 00

**Comment by msmith626** [comment]
Okay, the lvmlockd binary is in ESOS (1926c9f) -- now what? Is it like CLVM where a RA is supposed to manage it? Or a separate rc script?

--Marc

**Comment by feldsam** [comment]
Hi, should be just rc script, because shared volumes works even without corosync stack. It can use "sanlock" instead dlm. https://git.fedorahosted.org/cgit/sanlock.git/

**Comment by msmith626** [comment]
In ours we configured it without the sanlock option... I thought the
methods were mutually exclusive, but maybe not? So do we need an rc script
and a RA? I'm pretty sure you were the one that objected to not having DLM
controlled with an RA -- wouldn't we want lvmlockd controlled by an RA too?

Marc

**Comment by feldsam** [comment]
Hi, I think that we don't need RA, just rc script, also in resource-agents repo is not RA for lockd.

**Comment by msmith626** [comment]
I just committed this with the rc script... new image should be posted in a couple of hours. To use, you'll need to enable rc.lvmlockd in /etc/rc.conf and disable rc.lvm2. You will also need to enable rc.dlm in /etc/rc.conf and should probably make sure rc.clvmd is disabled, and no DLM/CLMV resources are in your cluster configuration since these would now be handled by init.

I haven't tested this yet, so let me know how it goes.


--Marc

**Comment by msmith626** [comment]
Hi Kristian,

Did you by chance have a moment to test this yet?

--Marc

**Comment by feldsam** [comment]
Hi Marc, unfortunately I didn't have time to test it yet.

**Comment by msmith626** [comment]
Okay, I'm going to close this issue for now, and if we have any problems, we can re-open or create a new issue. I plan to also test it myself in the next week or so.

--Marc

**Comment by remy1991** [comment]
Has any tried using lvmlockd on debian/ubuntu? I do see any packages for either of them so I thought of compiling it from source. How to build it for debian/ubuntu?

**Comment by feldsam** [comment]
hello, for clusters I preffer to use latest centos 7.3+ or Fedora.

**Comment by remy1991** [comment]
But in my case I am restricted to ubuntu and clvm/dlm is giving a lot of issues due to abandoned lockspaces. Hence actively looking for alternatives and lvmlockd looks promising. 
 
> hello, for clusters I preffer to use latest centos 7.3+ or Fedora.

**Comment by msmith626** [comment]
ESOS has included lvmlockd for quite some time and includes an init/rc
script (/etc/rc.d/rc.lvmlockd) or you could use a cluster RA (if one
exists).

--Marc

**Comment by axxana** [comment]
Hi,
LVMLOCKD is not a default feature during build process of LVM2.2.02.173.
When trying to build with LVMLOCKD (--enable-use-lvmlockd?), the "./configure" pass (no errors), however, there is NO lvmlockd executable under /sbin.
When trying to build with SANLOCK (--enable-lvmlockd-sanlock), an error appears:
  checking_ whether to build lvmlockdsanlock... yes
  checking for LOCKD_SANLOCK... no
  configure: error: bailing out

Please advise.

Thanks.

**Comment by remy1991** [comment]
You would need to install libsanlock1-client and make sure sanlock
libraries are present where you are compiling. Apart from that, I faced
similar issue and hence provided certain cflags to dodge the error.

**Comment by msmith626** [comment]
Is that a feature request... include sanlock support with ESOS?

**Comment by axxana** [comment]
I think that it is better to be included. Otherwise, at least the build procedure should be much more simple; an additional configuration flag rather than a process; install an additional package, add libs path, add CFLAGS...

Thanks.

**Comment by msmith626** [comment]
Issue # 202 has been opened for this enhancement request.

--Marc
