### ISSUE TITLE
TUI segfaults and dies

### ISSUE THREAD

**Issue by dswartz** [parodyne/esos#177]
Build from brand-new master.  Screenshot attached...
![image0012](https://cloud.githubusercontent.com/assets/2582198/15629336/855f53c2-24e4-11e6-8d9a-0bde85c3c927.jpg)

**Comment by msmith626** [comment]
Can you run with gdb and give me a backtrace please? Let me know if you
need a hand with the syntax.


Marc

**Comment by dswartz** [comment]
On 2016-05-28 19:22, Marc A. Smith wrote:
> Can you run with gdb and give me a backtrace please? Let me know if
> you
>  need a hand with the syntax.

where is gdb?  i booted production and debug kernels and don't see it 
anywhere?  Or do I have to build with gdb?

**Comment by msmith626** [comment]
You have to build with gdb... I think I see the issue; can you try the
attached binary (esos_tui goes in /usr/local/bin/).


--Marc

**Comment by dswartz** [comment]
Okay, I got it built with gdb.  Here is the backtrace.  Let me know if 
you need anything else...

**Comment by dswartz** [comment]
On 2016-05-29 12:03, Marc A. Smith wrote:
> I just pushed 999bb3e [1] -- can you try it now with that?

Building now...

**Comment by dswartz** [comment]
On 2016-05-29 12:03, Marc A. Smith wrote:
> I just pushed 999bb3e [1] -- can you try it now with that?

that fixed it, thanks!

p.s. something changed in the GUI?  how do i get to the 'quit to command 
line'?  Or am I just supposed to hit CTRL-c?

**Comment by msmith626** [comment]
Yeah, hit "i" as usual to open the Interface menu, and then you can exit to
shell, quit, etc.

--Marc

**Comment by dswartz** [comment]
On 2016-05-29 22:30, Marc A. Smith wrote:
> Yeah, hit "i" as usual to open the Interface menu, and then you can
> exit to
>  shell, quit, etc.

Well duh on me :)  The "Interface" menu moved from the upper right 
corner, and I didn't see it.  Works fine, thanks!
