### ISSUE TITLE
Helpful utility?

### ISSUE THREAD

**Issue by dswartz** [parodyne/esos#179]
http://linux.dell.com/cgi-bin/cgit.cgi/sys-admin-tools.git/plain/list-pcie-ports.sh

Does this:

[root@esos1 ~]# ./list-pcie-ports.sh -t 
PCIE_X4_1: x4 PCI Express
PCIE_X4_2: x4 PCI Express
PCIE_X8_3: x8 PCI Express
PCIE_X8_4: x8 PCI Express
PCIE_X4_5: x4 PCI Express
PCIE_X4_6: x4 PCI Express
PCIE_X4_7: x4 PCI Express

and
[root@esos1 ~]# ./list-pcie-ports.sh -l
PCIE_X4_1: Empty
PCIE_X4_2: Empty
PCIE_X8_3: Intel Corporation 82599ES 10-Gigabit SFI/SFP+ Network Connection 
        Subsystem: Intel Corporation Ethernet Server Adapter X520-2
        Flags: bus master, fast devsel, latency 0, IRQ 20
        Memory at eff00000 (64-bit, non-prefetchable) [size=512K]
        I/O ports at dcc0 [size=32]
        Memory at efef8000 (64-bit, non-prefetchable) [size=16K]
        Expansion ROM at efe00000 [disabled] [size=512K]
        Capabilities: [40] Power Management version 3
        Capabilities: [50] MSI: Enable- Count=1/1 Maskable+ 64bit+
        Capabilities: [70] MSI-X: Enable+ Count=64 Masked-
        Capabilities: [a0] Express Endpoint, MSI 00
        Capabilities: [100] Advanced Error Reporting
        Capabilities: [140] Device Serial Number 90-e2-ba-ff-ff-1d-1b-cc
        Capabilities: [150] Alternative Routing-ID Interpretation (ARI)
        Capabilities: [160] Single Root I/O Virtualization (SR-IOV)
        Kernel driver in use: ixgbe

PCIE_X8_4: Empty
PCIE_X4_5: Empty
PCIE_X4_6: LSI Logic / Symbios Logic SAS2008 PCI-Express Fusion-MPT SAS-2 [Falcon] 
        Subsystem: Dell 6Gbps SAS HBA Adapter
        Flags: bus master, fast devsel, latency 0, IRQ 36
        I/O ports at bc00 [size=256]
        Memory at dfeb0000 (64-bit, non-prefetchable) [size=64K]
        Memory at dfec0000 (64-bit, non-prefetchable) [size=256K]
        Expansion ROM at dfd00000 [disabled] [size=1M]
        Capabilities: [50] Power Management version 3
        Capabilities: [68] Express Endpoint, MSI 00
        Capabilities: [d0] Vital Product Data
        Capabilities: [a8] MSI: Enable- Count=1/1 Maskable- 64bit+
        Capabilities: [c0] MSI-X: Enable+ Count=15 Masked-
        Capabilities: [100] Advanced Error Reporting
        Capabilities: [138] Power Budgeting <?>
        Kernel driver in use: mpt3sas

PCIE_X4_7: Intel Corporation 82571EB Gigabit Ethernet Controller 
        Subsystem: Intel Corporation PRO/1000 PT Dual Port Server Adapter
        Flags: bus master, fast devsel, latency 0, IRQ 41
        Memory at dff80000 (32-bit, non-prefetchable) [size=128K]
        Memory at dffa0000 (32-bit, non-prefetchable) [size=128K]
        I/O ports at acc0 [size=32]
        Capabilities: [c8] Power Management version 2
        Capabilities: [d0] MSI: Enable+ Count=1/1 Maskable- 64bit+
        Capabilities: [e0] Express Endpoint, MSI 00
        Capabilities: [100] Advanced Error Reporting
        Capabilities: [140] Device Serial Number 00-15-17-ff-ff-8e-e4-d4
        Kernel driver in use: e1000e

**Comment by msmith626** [comment]
Yes, I like it. I've committed this on my machine and will be on GH with the next push. Thanks.

--Marc
