### ISSUE TITLE
System hangs "Assembling software RAID devices..."

### ISSUE THREAD

**Issue by dswartz** [parodyne/esos#180]
This is sandy-bridge xeon on SM mobo.  My backup server.  Wanted to boot it from esos flash to try out.  Hangs as above.  100% reproducible.  Oddly, AFAIK, there are not now, nor have there ever been any MD raid devices on this system.  It has two 100GB or so SSD mirrored (running OmniOS) and two 2TB sata drives (also mirrored) for the data pool.  I'd be happy to comment out the mdraid crap, but I'm not sure how to get to a command prompt to do this.  I'm happy to get you any diagnostic info you need...
![image0016](https://cloud.githubusercontent.com/assets/2582198/15941431/1a1ddfe8-2e4e-11e6-8229-41b7afc793ef.jpg)

**Comment by msmith626** [comment]
Is this from the master branch or 0.1.x?

**Comment by dswartz** [comment]
On 2016-06-09 14:28, Marc A. Smith wrote:
> Is this from the master branch or 0.1.x?

master.  for zfs.  this is the same image i built and ran on my primary 
storage server a couple of days ago...

**Comment by msmith626** [comment]
So, the mdadm binary is hanging on one of your systems, but we don't know
why. Let me think for a minute if there is a good way to bypass that, but
maybe just disconnecting any storage/drives temporarily may help. Sounds
like its hanging when scanning/assembling MD arrays, and if you don't have
any, maybe its stuck trying to read from some block device.

**Comment by dswartz** [comment]
On 2016-06-09 14:43, Marc A. Smith wrote:
> So, the mdadm binary is hanging on one of your systems, but we don't
> know
>  why. Let me think for a minute if there is a good way to bypass that,
> but
>  maybe just disconnecting any storage/drives temporarily may help.
> Sounds
>  like its hanging when scanning/assembling MD arrays, and if you don't
> have
>  any, maybe its stuck trying to read from some block device.

Yeah, I have no idea which one though.  I googled a bit, but came up 
empty.  Be nice if there was a single-user grub mode for esos, so I 
could 'vi' rc.2 or whatever and disable MD (since I'm not using MD at 
all.)  Puzzled as to why it thinks any of those 4 disks might be part of 
an MD array (and why it's *still* sitting there abusing itself.)

**Comment by msmith626** [comment]
Yeah, just unplug all of the disks so it can boot up, then configure the
basics and disable MD RAID in /etc/rc.conf.

**Comment by dswartz** [comment]
Unfortunately, I'm at work right now :)  I'm getting to it via KVM.  Hmmm, I bet I can disable the sata controller, reboot, disable MD, etc...  I'd give anything to figure out wtf its problem is, though.  Is it worth doing an md scan or whatever from the shell once its up?  Any useful info you might want?

**Comment by msmith626** [comment]
Yeah, I want log data and to know what the mdadm process is doing. Once you
have it up and running with the disks connected (with MD disabled) you can
run the command string by hand from rc.mdraid and observe logs, process
state, etc.

Thanks.

And I'll look into supporting the "single" keyword to enter single-user
mode -- shouldn't be difficult.

--Marc

**Comment by msmith626** [comment]
Hmm... "telinit 1" works and brings my system into run-level 1 (single user
mode). Maybe "single" isn't the keyword anymore? I'll investigate...

**Comment by dswartz** [comment]
Well, that sucks.  I could have sworn this bios had a way to disable the sata controller.  I guess not so has to wait until I get home.

**Comment by dswartz** [comment]
No, what I meant was 'single' from the grub command line...

**Comment by dswartz** [comment]
Okay, I figured it out.  Rather than pull disks, I disabled mdraid in rc.conf and reimaged the flash drive.  Here is what is happening:

`[root@esos2 ~]# mdadm -v --assemble --scan || echo THIS IS WHY IT HUNG   
mdadm: looking for devices for further assembly
mdadm: no recogniseable superblock on /dev/sde4
mdadm: no recogniseable superblock on /dev/sde3
mdadm: no recogniseable superblock on /dev/sde2
mdadm: no recogniseable superblock on /dev/sde1
mdadm: Cannot assemble mbr metadata on /dev/sde
mdadm: no recogniseable superblock on /dev/sdd9
mdadm: no recogniseable superblock on /dev/sdd1
mdadm: Cannot assemble mbr metadata on /dev/sdd
mdadm: no recogniseable superblock on /dev/sdc9
mdadm: no recogniseable superblock on /dev/sdc1
mdadm: Cannot assemble mbr metadata on /dev/sdc
mdadm: no recogniseable superblock on /dev/sdb9
mdadm: Cannot assemble mbr metadata on /dev/sdb1
mdadm: Cannot assemble mbr metadata on /dev/sdb
mdadm: no recogniseable superblock on /dev/sda9
mdadm: Cannot assemble mbr metadata on /dev/sda1
mdadm: Cannot assemble mbr metadata on /dev/sda
mdadm: no recogniseable superblock on /dev/ram15
mdadm: no recogniseable superblock on /dev/ram14
mdadm: no recogniseable superblock on /dev/ram13
mdadm: no recogniseable superblock on /dev/ram12
mdadm: no recogniseable superblock on /dev/ram11
mdadm: no recogniseable superblock on /dev/ram10
mdadm: no recogniseable superblock on /dev/ram9
mdadm: no recogniseable superblock on /dev/ram8
mdadm: no recogniseable superblock on /dev/ram7
mdadm: no recogniseable superblock on /dev/ram6
mdadm: no recogniseable superblock on /dev/ram5
mdadm: no recogniseable superblock on /dev/ram4
mdadm: no recogniseable superblock on /dev/ram3
mdadm: no recogniseable superblock on /dev/ram2
mdadm: no recogniseable superblock on /dev/ram1
mdadm: no recogniseable superblock on /dev/ram0
mdadm: No arrays found in config file or automatically
THIS IS WHY IT HUNG
`
None of the 4 disks ever had anything like a normal filesystem, so mdadm bitched, and exited.  This, of course, blew away everything else.

**Comment by msmith626** [comment]
Ah, good thought modifying the source (I forget you build from source). I
don't understand what you mean -- if it does that on the shell, why doesn't
it do the same thing during init? You lost me...

--Marc

**Comment by dswartz** [comment]
On 2016-06-10 19:02, Marc A. Smith wrote:
> Ah, good thought modifying the source (I forget you build from
> source). I
>  don't understand what you mean -- if it does that on the shell, why
> doesn't
>  it do the same thing during init? You lost me...

I lost myself too.  Not enough sleep last night :)  I misread the eval 
statement and thought it was going to the exit because mdadm returned 
non-zero.  '||' doesn't work that way - duh!  It must have somehow 
returned a zero or something.  The madadm man page is f*cking useless to 
figure this out :(  Still looking...

**Comment by msmith626** [comment]
Other boot services come up in init, and if your trying mdadm after all
that, the effects could be different.

**Comment by dswartz** [comment]
Right, makes sense.  So instead I added some debug crap to /etc/rc.d/rc.mdraid and re-ran the 'make image' sequence.  Rebooted and it hangs in mdadm.  I'm pretty sure that's what is happening, since the echo of the command status from mdadm completion never occurs.  Screenshot enclosed...
![image0017](https://cloud.githubusercontent.com/assets/2582198/15987305/f97e559c-2ff1-11e6-8d67-fcb98456c8d1.jpg)

**Comment by dswartz** [comment]
Well, I'm about ready to give up.  I've had the most amazing bad luck with the whole build from source route.  To recap: I get the above hang.  I disabled mdraid and try again, and now it hangs in the LVM code.  So I disable *that* and try again (figuring once I get the network up, I can ssh in and try to get a backtrace of the hung mdadm or whatever.  Only now... it's hanging "Checking all filesystems..."  It's almost like if I change "too much" and do another 'make image', something is getting fucked up.  But doing a from scratch build takes 2-3 hours.  I'm going to take one more shot at this: do a complete build from scratch in a brand-new directory.  I will disable mdraid and lvm2 in rc.conf, build a first image, and try that.  If it doesn't work, I give up.  I'm sorry, but this is like performing a self-appendectomy.  I totally understand this is a master/unstable/bleeding-edge build situation, but it's the only way I can get zfs, and there are too many advantages to zfs to want to go back to xfs or ext4 or whatever...

**Comment by msmith626** [comment]
Is it possible its something with your specific hardware? While it may be
the "master" (development) branch, its very close to becoming the next
stable branch. I personally run it on a lot of different hardware, and
don't have any problems. I'm aware of many others using master in
production too (same boat as you, where they need the new features) and I
haven't heard of any problem like you describe here.

Can you try the image you've built on different hardware and see if that
makes a difference? Maybe its your system hanging / locking up and
something related to disk (local SAS/RAID disk)?

I checked the linux-raid mailing list and didn't see anything related to
the hang with mdadm. And its even more odd you can't reproduce it after the
rc/init start-up is complete.

**Comment by dswartz** [comment]
It's already running on my primary storage server (dell poweredge r905).  The problematic HW is a SM x9scl-f with xeon (sandy bridge).  I've booted and run a half-dozen other distros on it.  I'm going to try one last experiment: a stock esos 0.1.9 without zfs.  I don't care about actual access to the pool here - just trying to eliminate the 'build from source' as an issue.

**Comment by dswartz** [comment]
I would be delighted if zfs was baked into esos :)

**Comment by dswartz** [comment]
And... a stock 0.1.9 booted flawlessly.  Either it's from something since April (when 0.1.9 came out), or it's yet another build f*ckup (with no errors or anything.)  Let me know if (or when) ZFS is available in production.  Please don't get me wrong, I know you put in a ton of effort on this - not saying I could do any better, but the build from source route has been an unmitigated disaster for me, and it just ain't worth it...

**Comment by msmith626** [comment]
So, build from source is not working for you? I thought I fixed your Ubuntu
build issues? Building software from source is definitely not something
normal for most modern Linux users -- the package management systems have
come a long ways in the current Linux distributions.

I'm not saying there couldn't be stability issues in the master branch --
it uses a much newer kernel (4.5.x) then the 0.1.x branch, I just haven't
had any issues myself, and neither have any other users (at least none
reported). But without any error messages, or anything to go on, I'm not
even sure where to look to diagnose your problem.

So, if 0.1.9 is stable, why not try the latest "master" image posted in the
ESOS downloads area? This way you can see if its something wrong with your
build (unlikely) or some type of issue for your hardware in Linux 4.5.


--Marc

**Comment by dswartz** [comment]
You resolved the build failures.  Maybe there is some timing issue hosing me.  It like you said, maybe a recent change in the tree?  As far as your suggestion, I'm confused.  That's exactly what I did.  But it doesn't have zfs?  Or are you saying there is a 0.1.9 prebuilt image with zfs already?

**Comment by msmith626** [comment]
There is 0.1.x branch where 0.1.9 comes from (no ZFS support). There is
also a master branch and master version packages are posted in the
downloads area... ZFS is supported in master, but not enabled by default.
The official master packages provided on the ESOS web site do not have ZFS
enabled but it would be worthwhile to test your machine with that so you
can rule out your possible build issue.

**Comment by dswartz** [comment]
Ok...

**Comment by dswartz** [comment]
Just booted from 
http://download.esos-project.com/packages/master/esos-master_cf55fc1_dgvs.zip. 
  Comes up just fine.  So either it's something funky with zfs/spl or I'm 
getting boned by some build heisenbug...

**Comment by msmith626** [comment]
So the next step would be to modify your build from source image and
comment out the ZFS stuff and see if it still hangs.

**Comment by dswartz** [comment]
In process...

**Comment by dswartz** [comment]
Okay, seems ZFS related.  Did the identical build from master, only with no enabling of ZFS in the configuration step.  Booted like champ...

**Comment by msmith626** [comment]
It seems like many months back you had some weird problem with something
related to ZFS hanging... Or was that something else? I had thought you
reported it to ZoL issue tracker and they didn't know what to make of it?
Maybe it was something else, I don't remember...

**Comment by dswartz** [comment]
It was ZoL issue #3330.  It involved zpool import hanging if one or more zvols are present.  It was supposedly resolved in 0.6.5.6, and master uses 0.6.5.7.  Also, I have confirmed that the host in question does not have any zvols - either in the root pool (rpool) or the data pool (tank-copy).  Also, that issue described a hang doing 'zpool import'.  In this case, the pools are both imported and it has moved on to other things.  I am suspicious of the fact that we are running a very new kernel...

**Comment by dswartz** [comment]
This is all frustrating.  I had been using OmniOS for the backup server, cuz it worked fine.  Well, I got a brocade 10gbe switch off ebay, and it works like a champ.  Except.  Something in the OmniOS ixgbe driver sucks and generates a sh*tload of CRC errors, which hoses the TCP performance down to 1gbe levels.  So I decided to replace it with ESOS.  Except I can't :(  I'm giving serious though to installing esxi on that server, and installing OmnisOS as a guest with all but 2GB RAM allocated and passing the HBA through with pci passthrough.  That should fix the ixgbe issue, as I could give it a vmxnet3 vnic.  Gross and ugly, but I'm not sure what else to do at this point (aside from run non-ZFS on the backup server, which is not appealing...)

**Comment by msmith626** [comment]
Yeah, the kernel sounds likely. I wish they would announce already what the
next long term support branch for Linux will be. I'll look and see if there
are any interesting fixes in 4.5.

Marc

**Comment by dswartz** [comment]
It's got to be something odd, since the primary server is running pretty much the same SW and works just fine :(

**Comment by msmith626** [comment]
And you weren't able to obtain any kernel logs (if any)?

**Comment by dswartz** [comment]
Hmmm, I just assumed I wouldn't be able to.  I wonder if I can access them somehow?  I guess I could boot the server from a linux rescue cd and mount the log partition?  Or some other way?

**Comment by msmith626** [comment]
I believe sshd is started before the MD RAID stuff (I presume that is where
it still hangs)... so if you had a network configuration, maybe you could
SSH in after it hangs?

**Comment by dswartz** [comment]
I notice there seems to be a primary/secondary partition feature now?  If so, could I do this?

Install non-ZFS (already done) on flash.
Boot to complete set up.
Set up network configuration.
Copy over zip file with ZFS version.
Unzip it.
do ./install.sh of ZFS version, which *should* go to secondary partition.
(assuming it hangs again)
power cycle
boot from non-ZFS partition (secondary now?)
mount logs partition and look for evidence

?

**Comment by msmith626** [comment]
Yeah, those steps would work, but logs aren't stored directly to persistent
storage -- they are sync'd, so fetching the logs isn't an option. Yes, I
realize that is not the best situation, so something I've thought of to
work more like ESXi and choose persistent storage for logs. Nothing we can
do about it right now though.

Have you tried booting the ESOS debug kernel? If it is some type of a
kernel hang, you might have more luck with that.

**Comment by dswartz** [comment]
I'm pretty sure I tried the debug kernel to no avail...  I don't think it's actually a kernel hang, but various startup elements exiting, which blows away the init process (or whatever is running at the time.)  My speculation when mdadm hung was that the return code was zero, so the ' || exit 1' blew us away.  Didn't end up looking at the other pieces of the puzzle...

**Comment by dswartz** [comment]
Hmmm, got to be triggered by some specific HW.  I just built again and booted in a vmware VM.  Comes up fine.  Push it to my server, and same old hang.  I might try installing vsphere on that server and install esos as a guest, and pass the HBA in and see how it works.  Other than that, I'm stuck...

**Comment by dswartz** [comment]
Okay, I guess I'm done.  I was willing to lose some (but not a lot) of performance by running esos in a esxi VM with the lsi hba passed through.  Copy over the 8GB ZFS build image and boot.  "No pools to import".  WTF.  Look through the logs and see this:

[    0.549764] mpt3sas version 09.102.00.00 loaded
[    0.550431] mpt2sas_cm0: 64 BIT PCI BUS DMA ADDRESSING SUPPORTED, total mem (26619756 kB)
[    0.606203] mpt2sas_cm0: MSI-X vectors supported: 16, no of cores: 3, max_msix_vectors: -1
[    0.608995] mpt2sas0-msix0: PCI-MSI-X enabled: IRQ 56
[    0.609199] mpt2sas0-msix1: PCI-MSI-X enabled: IRQ 57
[    0.609399] mpt2sas0-msix2: PCI-MSI-X enabled: IRQ 58
[    0.609602] mpt2sas_cm0: iomem(0x00000000fd2f0000), mapped(0xffffc90003660000), size(65536)
[    0.609957] mpt2sas_cm0: ioport(0x0000000000007000), size(256)
[    0.718821] mpt2sas_cm0: Allocated physical memory: size(16526 kB)
[    0.719074] mpt2sas_cm0: Current Controller Queue Depth(9979),Max Controller Queue Depth(10240)
[    0.719431] mpt2sas_cm0: Scatter Gather Elements per IO(128)
[   30.764020] mpt2sas_cm0: _base_event_notification: timeout
[   30.765970] mpt2sas_cm0: sending message unit reset !!
[   30.767707] mpt2sas_cm0: message unit reset: SUCCESS
[   31.396852] mpt2sas_cm0: failure at drivers/scsi/mpt3sas/mpt3sas_scsih.c:8592/_scsih_probe()!
[   31.427080] mptctl: Registered with Fusion MPT base driver
[   31.427294] mptctl: /dev/mptctl @ (major,minor=10,220)

This may not be what is biting me in raw-metal mode, but either way, I've spent *way* too much time and effort on this :(

**Comment by msmith626** [comment]
I Google'd your error message from mpt2sas and found this post:
http://www.spinics.net/lists/linux-scsi/msg95377.html

I didn't go through it all the way, but it sounds VERY similar to behavior
you're using... and would explain why you get hangs when any disk related
tools are scanning (eg, mdadm).

I'll read through the rest of it and see if there is a fix...

**Comment by msmith626** [comment]
Does that describe your situation? Can you try adding
"mpt3sas.msix_disable=1" to your GRUB boot options (temporary is fine
to test if you wish).

**Comment by dswartz** [comment]
Well, that looks suspicious for sure.  I am doing a fresh build and will report back :)

**Comment by dswartz** [comment]
Too good to be true :(  So, the above may explain the issue I had running esos/zfs virtualized, but it's not the culprit on bare metal.  I tried the above option, and also 'pci=nomsi' as the bug thread mentions.  Neither helped.  I'm going to comment out the zfs pool starting stuff and see if it comes up okay, and if so, what happens if I do the pool import at that point...

**Comment by dswartz** [comment]
Ah, I think I know what's going on.  I commented out ALL the zfs stuff and she came up just fine.  I then did "/usr/sbin/zpool import -d /dev/disk/by-id -a" and got "PANIC: blkptr at ffff8807cb4b0000 has invalid CHECKSUM 10".  I seem to recall seeing this on the ZoL list - my pool on this host was created using OmniOS which has a few new checksum types.  Should not be causing a panic though.  I think I need to destroy the old pool and recreate under esos.

**Comment by dswartz** [comment]
One thing I don't understand though: the zpool code in /etc/rc.d/rc.2 does this:

    /bin/echo "Importing ZFS pools..."
    if [ -f "/etc/zfs/zpool.cache" ]; then
        /usr/sbin/zpool import -c /etc/zfs/zpool.cache -a
    fi
    /usr/sbin/zpool import -d /dev/disk/by-id -a

But when I look in /etc, I do not find a zfs directory?  This means no cache file :(

**Comment by msmith626** [comment]
Yeah, I think if you haven't ran "zpool" it won't create that file. I
believe that file is created after creating a new storage pool. And didn't
you have an issue on your machine that we fixed with sysconfdir being
/usr/etc instead of /etc? I believe that change/fix was already committed...

**Comment by dswartz** [comment]
I did create a pool though.  The issue is not the missing cache file, it's that /etc/zfs doesn't exist.  I confirmed it doesn't exist even on my primary storage server that is otherwise working okay...

**Comment by msmith626** [comment]
It exists on my machine (ESOS + ZFS image) and the cache file is created
when I create a storage pool. Does /usr/etc/zfs exist on your machine?
Maybe your source isn't updated?

**Comment by dswartz** [comment]
Very weird.  I just did a 100% fresh build last night from master.  The box I am working on now:

[root@esos2 ~]# ls -la /usr/etc/zfs
total 0
drwxr-xr-x    3 root     root            60 Jun 22 10:57 .
drwxr-xr-x    3 root     root            60 Jun 22 10:57 ..
drwxr-xr-x    2 root     root           240 Jun 22 10:57 zed.d
[root@esos2 ~]# zpool status
  pool: tank
 state: ONLINE
  scan: none requested
config:

        NAME                           STATE     READ WRITE CKSUM
        tank                           ONLINE       0     0     0
          wwn-0x11997640237263114240x  ONLINE       0     0     0

errors: No known data errors
[root@esos2 ~]# ls -la /etc/zfs
ls: /etc/zfs: No such file or directory
[root@esos2 ~]#

**Comment by msmith626** [comment]
Did you confirm the --sysconfdir entry exists in your Makefile for zfs and
spl? Maybe you didn't run configure script? Or maybe I didn't push those
changes through? I can check shortly...

**Comment by dswartz** [comment]
542  git clone https://github.com/parodyne/esos.git
  543  cd esos/
  544  git checkout master
  545  history|grep confiure
  546  history|grep configure
  547  ./configure --enable-zfs=yes
  548  autoconf 
  549  ./configure --enable-zfs=yes
  550  make fetch && make extract

root@esos-buildbot:~/esos/work/build# grep sysconfdir spl-0.6.5.7/Makefile
sysconfdir = ${prefix}/etc
root@esos-buildbot:~/esos/work/build# grep sysconfdir zfs-0.6.5.7/Makefile
sysconfdir = ${prefix}/etc

I'm still confused.  I know you have a ramdisk filesystem and only subsets of root dirs are actually on the usb drive, no?  What makes /etc/zfs be there?

**Comment by msmith626** [comment]
I'll look in a bit and get back to you.

**Comment by dswartz** [comment]
I think at this point, maybe this issue should be closed?  If there is something you need to push to fix /etc/zfs being missing, that's another matter?

**Comment by msmith626** [comment]
Bah, that was my bad... was committed on my machine but not pushed:
commit a88b22b2291b4a515b74571d6dd756877b2d3045
Author: Marc A. Smith <marc.smith@parodyne.com>
Date:   Wed Jun 8 15:41:22 2016 -0400

    fix for ZFS build inconsistencies by specifying '--sysconfdir' for both
spl and zfs

Just did the push... update and try now. Sorry!


--Marc

**Comment by dswartz** [comment]
Rebuilding now...

**Comment by dswartz** [comment]
that did the trick!

[root@esos2 ~]# zpool create -f test /dev/disk/by-id/wwn-0x9328731653360930818x
[root@esos2 ~]# zpool status
  pool: test
 state: ONLINE
  scan: none requested
config:

        NAME                          STATE     READ WRITE CKSUM
        test                          ONLINE       0     0     0
          wwn-0x9328731653360930818x  ONLINE       0     0     0

errors: No known data errors
[root@esos2 ~]# ls -l /etc/zfs/
total 4
drwxr-xr-x    2 root     root           240 Jun 23 09:14 zed.d
-rw-r--r--    1 root     root          1188 Jun 23 09:24 zpool.cache

**Comment by dswartz** [comment]
Everything works now.  The hang turns out to be the task that is running the boot code panic'ing due to the incompatible zfs pool checksum type.  I blew away the pool, restored the zfs stuff in rc.2, rebooted, and everything works like a champ.  zpool.cache is there, all good.  Thanks!

**Comment by msmith626** [comment]
Okay, good deal.
