### ISSUE TITLE
health_chk.sh lists usage confusingly

### ISSUE THREAD

**Issue by dswartz** [parodyne/esos#181]
example:

Physical RAM check...
Total Memory:           32784416 kB
Used Memory:            17829624 kB
Available Memory:       14954792 kB
Memory used percent:    0.5

Disk (/ -> root tmpfs) space check...
Total Disk Space:       1536 MB
Used Disk Space:        533 MB
Avail. Disk Space:      1003 MB
Disk used percent:      0.3

the 0.5 and 0.3 are not percentages, but ratios compared to 1.0.  If it is going to say 'percent', shouldn't it be getting multiplied by 100?

**Comment by msmith626** [comment]
Yeah, I'll bite... so do you think we should change the word "percent" to "ratio", or do you think we should actually calculate the percentage value (multiply by 100) and include the percent symbol? Changing the word is the easiest, but maybe not the best?

--Marc

**Comment by dswartz** [comment]
I think a percentage ?

**Comment by msmith626** [comment]
This is fixed on my local copy, and will be pushed soon.

--Marc
