### ISSUE TITLE
check_zpools.sh needs to diagnose running as non-root

### ISSUE THREAD

**Issue by dswartz** [parodyne/esos#182]
I just wasted 4 hours trying to figure out why running this via nrpe gives:

ALL ZFS POOLS OK ()|

even though the pool is degraded. Turns out to be because nrpe runs as nagios, and zpool requires root privileges, even if just to list things.  I propose checking the user ID the plugin runs as and failing if it is not root.  I will open a PR for this.

**Comment by dswartz** [comment]
Actually, given how simple the change is, it might be easier to just hand you the fix, and you can throw it in with your next batch of changes?  Here is the output of 'git diff'.

diff --git a/contrib/check_zpools.sh b/contrib/check_zpools.sh
index 258ac42..7798084 100755
--- a/contrib/check_zpools.sh
+++ b/contrib/check_zpools.sh
@@ -49,6 +49,12 @@ if [ "${1}" = "--help" -o "${#}" = "0" ];
        exit ${STATE_UNKNOWN};
 fi
 #########################################################################
+# Ensure we are executing as root
+if [ `/usr/bin/id -u` != 0 ];
+       then
+       echo "UNKNOWN: this plugin must be executed with root privileges!"
+       exit ${STATE_UNKNOWN};
+fi
 # Get user-given variables
 while getopts "p:w:c:" Input;
 do

Proposed output:

[testuser@esos1 ~]$ /usr/libexec/check_zpools.sh -p ALL
UNKNOWN: this plugin must be executed with root privileges!

**Comment by dswartz** [comment]
Errrm, not real versed in markdown and such.  I needed backticks around the invocation of /usr/bin/id, but it removed them.  Escaping with a backslash didn't seem to do the right thing either...

**Comment by msmith626** [comment]
You mind doing a pull request? Might be cleaner that way. =)

--Marc

**Comment by dswartz** [comment]
Sure :)

**Comment by dswartz** [comment]
All set?

**Comment by dswartz** [comment]
PR #183.

**Comment by msmith626** [comment]
Done.
