### ISSUE TITLE
Download site is hosed?

### ISSUE THREAD

**Issue by dswartz** [parodyne/esos#184]
Tried downloading zip of 0.1.x and the DL speed is in the KB/sec.  From two different locations...

**Comment by msmith626** [comment]
Its a tiny server... I'm downloading a master image from it right now and
getting between 600-800 KB/sec which is what I normally see (nothing faster
than that usually). Is it still a problem or was it just a transient issue?

**Comment by dswartz** [comment]
On 2016-08-10 11:14, Marc A. Smith wrote:
> Its a tiny server... I'm downloading a master image from it right now
> and
>  getting between 600-800 KB/sec which is what I normally see (nothing
> faster
>  than that usually). Is it still a problem or was it just a transient
> issue?

Currently ongoing.  I'm not in a rush, just didn't know if it was an 
issue.  I will check if it finished when I get home...
