### ISSUE TITLE
Hyper-V synthetic devices drivers

### ISSUE THREAD

**Issue by defender52** [parodyne/esos#185]
Hi Mark,

Could you please include Hyper-V synthetic devices drivers (Linux integration services) to ESOS build?

The main idea is to create the analogue of Starwind Hyper-converged virtual SAN - to run both HA storage and HA Hyper-V cluster on the same physical server nodes. 
ESOS in such scenario should be installed as non-clustered virtual machine on each Hyper-V node.

"lsmod | grep hv" returns nothing so I assume these drivers are not installed.
It is also impossible to configure networking with TUI due to "ioctl siocethtool error".

TIA,
BR,
Alexander

**Comment by defender52** [comment]
error screen:
![error](https://cloud.githubusercontent.com/assets/16222810/18087804/a5d47a90-6ebf-11e6-9ed5-b0c29a5e4729.png)

**Comment by msmith626** [comment]
Hi,

Do you know specifically what kernel options need to be enabled (eg, which
CONFIG_* options)? Can you run "ifconfig -a" and post that output?

In the 'master' branch, this is what we have right now:
$ cat misc/linux-4.5.2.config | grep -i hyperv
CONFIG_HYPERVISOR_GUEST=y
# CONFIG_SYS_HYPERVISOR is not set
CONFIG_HYPERV_STORAGE=y
CONFIG_HYPERV_NET=y
CONFIG_HYPERV_KEYBOARD=y
# CONFIG_FB_HYPERV is not set
# CONFIG_HID_HYPERV_MOUSE is not set
CONFIG_HYPERV=y
CONFIG_HYPERV_UTILS=y
CONFIG_HYPERV_BALLOON=y

We typically don't build most kernel drivers as modules, they are built-in.


--Marc

**Comment by defender52** [comment]
Hi Mark,
Thank you for the fast response.

ifconfig –a
![ifconfig](https://cloud.githubusercontent.com/assets/16222810/18122803/c6162222-6f73-11e6-89ed-f9bf9a83ccb6.png)

BR,
Alexander

**Comment by defender52** [comment]
Unfortunately I'm not certain about kernel options to be enabled but as far as I know during the boot several modules should be started to support Hyper-V devices. 
For example, here is the output of "lsmod | grep hv" that I run on Debian VM started on Hyper-V:
# lsmod | grep hv
hid_base_hv           110681  1 hid_hyperv
hv_netvsc              57153  0
hv_utils               41841  0
hv_storvsc             47809  2
scsi_mod              199641  12 be2iscsi,ib_iser,iscsi_tcp,bnx2i,libcxgbi,libiscsi2,scsi_transport_iscsi2,scsi_dh,sg,libata,hv_storvsc,sd_mod
hv_vmbus               66209  4 hid_hyperv,hv_netvsc,hv_utils,hv_storvsc

These modules can be integrated into the list of supported Linux OS:
https://www.microsoft.com/en-us/download/details.aspx?id=46842
Some OSs have these modules integrated already (Debian, Ubuntu, etc.).

BR,
Alexander

**Comment by msmith626** [comment]
Ah, yeah, it appears that is a third-party software package provided by
Microsoft, and not part of the Linux kernel. I took a quick peak and it
appears to be source RPM files... I'm sure this could certainly be done,
but I don't have a lot of time to commit to this. Is there one specific
feature related to Hyper-V that you need? We already have several
Hyper-V-specific drivers enabled like the network and storage driver, so I
would think you get something already, just not the full integration
services.

--Marc

**Comment by SergiuPol** [comment]
Hi,

I am having the same problem as I intend to use ESOS in Hyper-V for the same purpose. An extra problem is that ESOS does not boot in Hyper-V VMs generations 2 (EFI based) but only in generation 1 (BIOS based).

**Comment by msmith626** [comment]
Hi,

Are you using an image from the '0.1.x' branch or from 'master'? Please try
using the latest package from the master branch. I can work with you to
enable whatever kernel options are needed, but currently we only support
BIOS booting with ESOS. I'll take a look and see what it would require to
support BIOS + EFI simultaneously.

So, ESOS boots using a generation 1 VM in your Hyper-V environment, but the
NIC configuration is the only problem? Or what else is wrong?


Thanks,

Marc

**Comment by IduVlad** [comment]
Hi Marc,

the latest package from master branch fixed the NIC problem on Hyper-V. Are there any updates on ESOS booting in Hyper-V gen 2 VM (EFI based)?

Thanks,
Vlad

**Comment by SergiuPol** [comment]
gen2 VMs are UEFI limited and cannot be changed to BIOS https://technet.microsoft.com/en-us/library/dn282285%28v=ws.11%29.aspx

Building ESOS on top of a modern Linux distro would solve the UEFI problem. I tried to use an external boot loader with UEFI support (GRUB2) to chainload the ESOS boot entry but failed.

If I install GRUB2 manually after ESOS is installed and manually add a boot entry for ESOS kernel, will it work?

**Comment by msmith626** [comment]
I'm not sure what that means with "building ESOS ontop of a modern Linux
distro"? ESOS only builds on Linux, and it builds just fine under Fedora 22
(modern enough I guess).

I believe a couple things need to change: The /boot FS needs to change to
FAT32 instead of ext2, and may need to be larger. The GRUB
installation/build needs to be updated to include the EFI bits. And I
believe the disk label needs to change to GPT instead of MBR.

These are mostly trivial changes, and they are on my to-do list, I just
can't get to them right now. So if you're interested in doing a pull
request, I can provide assistance. It just needs to be done, and needs
thorough testing.

--Marc

**Comment by IduVlad** [comment]
tried to make this changes on disk:
convert MBR to GPT; create ESP partition & change it to FAT32; install GRUB2 with EFI 
![hdd](https://cloud.githubusercontent.com/assets/24604641/21354659/a62dd8da-c6d3-11e6-8a2d-24d7688f4ca2.png)

when I try to boot manually in gen2 VM  from GRUB the initramfs is not loading
![grub2](https://cloud.githubusercontent.com/assets/24604641/21354679/b75d2598-c6d3-11e6-9138-eb20baebfb24.png)

**Comment by msmith626** [comment]
I think maybe there is a requirement that GRUB uses the special video stuff
instead of just text console when using EFI? Maybe we need to enable the
video stuff? That's what the error sounds like at least.

Nice work so far though!


Marc

**Comment by IduVlad** [comment]
I have enabled the video modules and the error is gone, still the boot process freezes at this point (grub debug enabled) 
![grub](https://cloud.githubusercontent.com/assets/24604641/21389135/b7a5aaba-c788-11e6-8df1-dd82f17d99f6.png)

**Comment by IduVlad** [comment]
Hi Marc,

on my next test, I have installed Fedora 25 with BIOS MBR  partition and made the convert changes to  GPT and EFI as I did for esos.  (both kernels: esos and fedora25 on the same boot partition) When I tried to boot them manually:
The esos kernel did not boot, seems to be old and does not support EFI handover.
![esos](https://cloud.githubusercontent.com/assets/24604641/21391893/2ff4e8b6-c796-11e6-8d1f-ea0dad7f77fc.png)
The Fedora 25 kernel was able to boot successfully after the convert.

**Comment by msmith626** [comment]
You're getting close! Ah, yes, I think there needs to be some kernel
options added in the kernel config. Let me look real quick, stand by. Are
you custom building ESOS? Or making these changes to a "live" USB flash
drive?

**Comment by msmith626** [comment]
Yes, it looks like some options are needed:

https://wiki.gentoo.org/wiki/EFI_stub_kernel#Configuration

**Comment by IduVlad** [comment]
I'm making this changes to a vhdx drive not building ESOS. Can you commit this options to ESOS?

**Comment by msmith626** [comment]
It sounds like this might really happen, so let me make a feature branch
and we'll do this together. I'll work on it this evening. Thanks.

--Marc

**Comment by msmith626** [comment]
Hi,

Okay, I'm a day late, but I started working on this tonight. I'm going with the modifications you tested so far, and I'm integrating those into a new feature branch. I'm going for gold with dual BIOS / EFI booting. Will have more to report back in a day or two, and be ready for you to test (hopefully).

--Marc

**Comment by msmith626** [comment]
Hi,

I think I have this working... I tested on my laptop and successfully booted in BIOS mode, and then in UEFI from the same media (image). Can you please try this image and let me know the result on your Hyper-V VM:
https://www.dropbox.com/s/s732tb26lyry4ql/esos-add_efi_boot_86f4cb3_dgvsz.zip?dl=0


--Marc

**Comment by IduVlad** [comment]
Hi Marc,

great job! I have just tested the image and works perfectly on both gen1 and gen2 VM now.

Vlad

**Comment by msmith626** [comment]
Thanks for the update/confirmation. I'll merge that feature branch into master later today. I may expand the /boot FS size a little first though.

So does ESOS run acceptably now on Hyper-V VM's (Gen1 + Gen2)? Is this issue safe to close?

--Marc
