### ISSUE TITLE
Feature request: Documentation for HA new scst, alua, syncro resource agents

### ISSUE THREAD

**Issue by feldsam** [parodyne/esos#186]
Hello, would be fine have documentation for updated and new scst, alua, syncro resource agents.

Thank you.

**Comment by msmith626** [comment]
Don't those fancy RA things have help/usage functions? :)

Yes, I will update. I want two wiki branches in GitHub... Any ideas or
alternative documentation place?

**Comment by feldsam** [comment]
Yes, I know that have help :).... You can just create new section for dev version, like 00_Dev wiki

**Comment by msmith626** [comment]
Hi,

Sorry for the long delay! I'm going through all documentation now and preparing for the new release branch.

I have moved all of the cluster configuration and RA information into one wiki page:
https://github.com/parodyne/esos/wiki/42_Cluster_Configuration


--Marc
