### ISSUE TITLE
please allow booting with low ram

### ISSUE THREAD

**Issue by mailinglists35** [parodyne/esos#187]
I only need to boot esos to rescue data from a system. To do this I only need the scst feature. This really requires little ram. I also want to try it in a vm and I don't have that much ram to allocate to a vm. I find it outrageous you refuse to boot without at least 3.5GB of ram.

![image](https://cloud.githubusercontent.com/assets/2054302/21223854/6a257fca-c2da-11e6-9a70-e8d644ba601d.png)

**Comment by mailinglists35** [comment]
![image](https://cloud.githubusercontent.com/assets/2054302/21224309/9fd5e4a0-c2dc-11e6-9337-05e239c70337.png)

**Comment by mailinglists35** [comment]
even with whole image loaded into ram, only uses under 500mb

**Comment by mailinglists35** [comment]
i mean it's great you put all work into an easy to use tui, but all i need from it is scst commands and ssh, as this appears to be the only project able to offer booting from a flash drive and share the local drives over iscsi

**Comment by mailinglists35** [comment]
my use cases being accessing a systems' drive when you cannot pull the drive out of that system (virus removal, repair os, rescue data)

**Comment by msmith626** [comment]
We may reduce this limit in future ESOS versions, but until then, feel free to modify the source and build.
