### ISSUE TITLE
Download site seems to be hosed?

### ISSUE THREAD

**Issue by dswartz** [parodyne/esos#190]
Tried multiple times from different hosts.  It downloads very slowly, then seems to die...

**Comment by feldsam** [comment]
Hi, I offered download mirror in past, my offer is still valid

**Comment by msmith626** [comment]
Dan: That server is pretty slow for me almost always... I'm downloading now
around 800 KB/sec. I looked at the server, and the disk wasn't full or
anything, but I still cleared some old files, but that shouldn't affect the
performance. Its a small server, and the download count is already over 20
today, so maybe just a couple other users downloading at the same time.

Kristian: Maybe I should reconsider and take you up on that... the files
are hosted here: http://download.esos-project.com/packages/

I assume you'll just setup rsync on your side to periodically sync to your
server. Let me know the URL and I'll post it on the ESOS project page.


--Marc


On Mon, Feb 27, 2017 at 11:26 AM, Kristian Feldsam <notifications@github.com

**Comment by feldsam** [comment]
Hi, I setuped VM with rssh shell on it. Hostname is esos-mirror.feldhost.cz

Username is esos
Password send you by email resp. send me pubkey

Files should be placed in `/home/esos/public` directory

**Comment by msmith626** [comment]
Thanks; rsync is setup with the mirror site and now available: http://esos-mirror.feldhost.cz/

I've also posted the URL on the main ESOS downloads page.

--Marc

**Comment by feldsam** [comment]
Hello, you should also add "EU Mirror" links to download tables
