### ISSUE TITLE
Master fails to compile - glib gio dependency issue

### ISSUE THREAD

**Issue by cloudguy23** [parodyne/esos#191]
Looks like there need to be a dependency for glib on elfutils in the Makefile.

Makefile.in:
```
glib: glibc zlib libffi util-linux elfutils
```

**Comment by msmith626** [comment]
Hi,

Interesting, I haven't encountered a build issue related to that yet. Is this for the '0.1.x' or 'master' branch of ESOS?


--Marc

**Comment by cloudguy23** [comment]
Hi Marc,

This is for master.  

Another snag, although not critical..   I'm building as root (I know, bad..), coreutils throws an error about being configured as root.   The following gets around that:

```
coreutils: glibc
        cd $(tgt_src_dir) && **FORCE_UNSAFE_CONFIGURE=1** && ./configure --prefix=/usr
        $(MAKE) --directory=$(tgt_src_dir)
        $(INSTALL) -m 0755 $(tgt_src_dir)/src/df $(IMAGE_DIR)/bin/df
        $(INSTALL) -m 0755 $(tgt_src_dir)/src/dd $(IMAGE_DIR)/bin/dd
        $(TOUCH) $(@)
```

**Comment by msmith626** [comment]
Thanks; I have both of these changes staged on my machine and will commit/push later this evening. Any other changes needed? You were able to complete the build successfully?

--Marc

**Comment by msmith626** [comment]
This has been committed and pushed (73db8e9). Please let us know if there are any more issues.

--Marc
