### ISSUE TITLE
TUI crash with ZFS

### ISSUE THREAD

**Issue by Hagbear** [parodyne/esos#192]
Hi,

I compiled ESOS a few days ago on CentOS7 with --enable-zfs. Everything works fine, but after I created a zvol on my zpool, the TUI from ESOS crashes if I try to create a vdisk_blockio:

"Something broke: the TUI exited with 139".

Version: master_9283a83_z

Greetings Marian

**Comment by msmith626** [comment]
Is there a core file in /tmp after the seg fault? If so, can you please
email to me directly.

Marc

**Comment by Hagbear** [comment]
thanks for your fast reply. where can i find your mail address?

**Comment by msmith626** [comment]
marc.smith@parodyne.com

**Comment by msmith626** [comment]
Fix will be applied to branches in the coming days:

diff --git a/tui/utility.c b/tui/utility.c
index 208f664..629f4f7 100644
--- a/tui/utility.c
+++ b/tui/utility.c
@@ -586,7 +586,7 @@ int getUsableBlockDevs(CDKSCREEN *cdk_screen,
                         snprintf(dir_name, MAX_SYSFS_PATH_SIZE, "%s/%s/size",
                                 SYSFS_BLOCK, blk_dev_name[dev_cnt]);
                         readAttribute(dir_name, tmp_buff);
-                        snprintf(blk_dev_size[dev_cnt], "%s", MISC_STRING_LEN,
+                        snprintf(blk_dev_size[dev_cnt], MISC_STRING_LEN, "%s",
                                 tmp_buff);
                         snprintf(dir_name, MAX_SYSFS_PATH_SIZE,
                                 "%s/%s/queue/logical_block_size",

**Comment by msmith626** [comment]
This is resolved (886670a19853f2f3ebadf4d559d4feebd43db1a8) and has been merged into master and 1.x.x -- a new release should post shortly (1.1.0).

Thanks for discovering this issue and reporting it.

--Marc
