### ISSUE TITLE
Centos 7.3 compile error

### ISSUE THREAD

**Issue by dawei1** [parodyne/esos#194]
Tried to compile from source with master branch on a fresh installed Centos 7.3 with zfs support. Got following message

make -C documentation/v9 doc
make[2]: Entering directory `/esos/work/build/drbd-utils-8.9.6/documentation/v9'
make -C ../../user/v9 drbdsetup
make[3]: Entering directory `/esos/work/build/drbd-utils-8.9.6/user/v9'
make[3]: `drbdsetup' is up to date.
make[3]: Leaving directory `/esos/work/build/drbd-utils-8.9.6/user/v9'
/usr/bin/xsltproc \
--xinclude --stringparam variablelist.term.break.after 1 \
http://docbook.sourceforge.net/release/xsl/current/manpages/docbook.xsl drbdsetup.xml
http://docbook.sourceforge.net/release/xsl/current/html/biblio.xsl:1: parser error : Document is empty
compilation error: file http://docbook.sourceforge.net/release/xsl/current/html/docbook.xsl line 60 element include
xsl:include : unable to load http://docbook.sourceforge.net/release/xsl/current/html/biblio.xsl
make[2]: *** [drbdsetup.8] Error 5
make[2]: Leaving directory `/esos/work/build/drbd-utils-8.9.6/documentation/v9'
make[1]: *** [doc] Error 2
make[1]: Leaving directory `/esos/work/build/drbd-utils-8.9.6'
make: *** [drbd-utils] Error 2

**Comment by msmith626** [comment]
Yeah, I've experienced that before... the drbd-utils package downloads some
stuff (docbook stuff) and sometimes that fails (randomly) with different
errors... HTTP type errors. You can try just picking up the build again
with "make" or "make -jX" and it should continue just fine.

Let me know if that doesn't solve it.

--Marc

**Comment by dawei1** [comment]
It turns out there are much more compile errors and I had to start over and over again but finally it did compile and generate the image. I was not sure if this is expected.

**Comment by msmith626** [comment]
A few other packages besides drbd-utils use the docbook stuff too, so maybe
SF was having some issues.

Glad to hear it built successfully.


Marc
