### ISSUE TITLE
Intel network interface driver

### ISSUE THREAD

**Issue by dawei1** [parodyne/esos#195]
I found the system does not have the driver for intel nic (igb, ixgbe) and VMware virtual nic (vmx), I was wondering if there is any tutorial about how to build it? Thanks.

**Comment by msmith626** [comment]
Why do you think those drivers aren't enabled?

[marc.smith@garbanzos esos]$ cat misc/linux-4.9.13.config | grep -i vmx
CONFIG_VMXNET3=y
[marc.smith@garbanzos esos]$ cat misc/linux-4.9.13.config | grep -i igb
CONFIG_IGB=y
CONFIG_IGB_HWMON=y
# CONFIG_IGBVF is not set
[marc.smith@garbanzos esos]$ cat misc/linux-4.9.13.config | grep -i ixgbe
CONFIG_IXGBE=y
CONFIG_IXGBE_HWMON=y
CONFIG_IXGBE_DCB=y
# CONFIG_IXGBEVF is not set

--Marc

**Comment by dawei1** [comment]
The intel X552 virtual function is not recognized by the system on VMware ESXi 6.5. I will try directpath I/O.

**Comment by msmith626** [comment]
It work okay using the direct I/O method?

**Comment by dawei1** [comment]
Yes pci passthrough works but I prefer using virtual function. I found in the kernel config the virtual function support is off by default so I am now re-compiling the system with the virtual function support and will try again.

**Comment by msmith626** [comment]
Okay, let me know which options need to be enabled and I can enable them in
ESOS.

Marc

**Comment by dawei1** [comment]
After add 'CONFIG_IXGBEVF=y' to /misc/linux-4.9.13.config, ESOS
successfully recognizes the intel X552 virtual function under VMware
Vsphere 6.5 hypervisor.

Da Wei / Ph.D. candidate
Electrical & Computer Engineering
University of Illinois at Urbana-Champaign

2017-04-11 19:21 GMT-05:00 Marc A. Smith <notifications@github.com>:

> Okay, let me know which options need to be enabled and I can enable them in
> ESOS.
>
> Marc
>
>

**Comment by msmith626** [comment]
There are other virtual function options for other adapters too:

[marc.smith@garbanzos esos]$ cat misc/linux-4.9.13.config | grep VF
# CONFIG_THUNDER_NIC_VF is not set
CONFIG_CHELSIO_T4VF=m
# CONFIG_IGBVF is not set
# CONFIG_IXGBEVF is not set
# CONFIG_I40EVF is not set
# CONFIG_NFP_NETVF is not set
# CONFIG_VFIO is not set
# CONFIG_PM_DEVFREQ is not set
CONFIG_VFAT_FS=y
# CONFIG_CRYPTO_DEV_QAT_DH895xCCVF is not set
# CONFIG_CRYPTO_DEV_QAT_C3XXXVF is not set
# CONFIG_CRYPTO_DEV_QAT_C62XVF is not set

It's probably a good idea to enable those, at least for the Intel drivers?

--Marc

**Comment by dawei1** [comment]
Yeap, agree.

2017-04-12 8:34 GMT-05:00 Marc A. Smith <notifications@github.com>:

> There are other virtual function options for other adapters too:
>
> [marc.smith@garbanzos esos]$ cat misc/linux-4.9.13.config | grep VF
> # CONFIG_THUNDER_NIC_VF is not set
> CONFIG_CHELSIO_T4VF=m
> # CONFIG_IGBVF is not set
> # CONFIG_IXGBEVF is not set
> # CONFIG_I40EVF is not set
> # CONFIG_NFP_NETVF is not set
> # CONFIG_VFIO is not set
> # CONFIG_PM_DEVFREQ is not set
> CONFIG_VFAT_FS=y
> # CONFIG_CRYPTO_DEV_QAT_DH895xCCVF is not set
> # CONFIG_CRYPTO_DEV_QAT_C3XXXVF is not set
> # CONFIG_CRYPTO_DEV_QAT_C62XVF is not set
>
> It's probably a good idea to enable those, at least for the Intel drivers?
>
> --Marc
>
>
