### ISSUE TITLE
EnhanceIO compile failure

### ISSUE THREAD

**Issue by dawei1** [parodyne/esos#197]
Compile on a fresh installed Redhat Linux 7.3 system encountered the following error:
[/home/ec2-user/esos/work/build/EnhanceIO-master_20151029/Driver/enhanceio/eio_conf.o] Error 1
make[3]: *** [_module_/home/ec2-user/esos/work/build/EnhanceIO-master_20151029/Driver/enhanceio] Error 2

Manually change the EnhanceIO code from the following git repo  solved the problem:
https://github.com/lanconnected/EnhanceIO/tree/4.10

Looks like the original EnhanceIO project is abandoned

**Comment by msmith626** [comment]
Right, that's why it's not enabled by default. Same for BTIER.

Marc
