### ISSUE TITLE
HP ACU util

### ISSUE THREAD

**Issue by michalkolar** [parodyne/esos#198]
Hi,

i want use hp web gui array configuration called "cpqacuxe".

How can I add lib for this app?

hpsmhd:
    linux-vdso.so.1 =>  (0x00007fffaa168000)
    libxml2.so.2 => /opt/hp/hpsmh/lib/libxml2.so.2 (0x00007f512dfd0000)
    libdl.so.2 => /lib64/libdl.so.2 (0x00007f512ddc8000)
    libm.so.6 => /lib64/libm.so.6 (0x00007f512db40000)
    libssl.so.1.0.0 => /opt/hp/hpsmh/lib/libssl.so.1.0.0 (0x00007f512d8d0000)
    libcrypto.so.1.0.0 => /opt/hp/hpsmh/lib/libcrypto.so.1.0.0 (0x00007f512d4c0000)
    libpcre.so.1 => /opt/hp/hpsmh/lib/libpcre.so.1 (0x00007f512d298000)
    libaprutil-1.so.0 => /opt/hp/hpsmh/lib/libaprutil-1.so.0 (0x00007f512d040000)
    libapr-1.so.0 => /opt/hp/hpsmh/lib/libapr-1.so.0 (0x00007f512ce00000)
    libpam.so.0 => not found
    libpam_misc.so.0 => not found
    libcurl.so.4 => /opt/hp/hpsmh/lib/libcurl.so.4 (0x00007f512cbb0000)
    libidn.so.11 => not found
    libz.so.1 => /opt/hp/hpsmh/lib/libz.so.1 (0x00007f512c998000)
    librt.so.1 => /lib64/librt.so.1 (0x00007f512c778000)
    libuuid.so.1 => /usr/lib64/libuuid.so.1 (0x00007f512c570000)
    libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007f512c338000)
    libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f512c118000)
    libc.so.6 => /lib64/libc.so.6 (0x00007f512bda8000)
    /lib64/ld-linux-x86-64.so.2 (0x00007f512e320000)
    libpam.so.0 => not found
    libpam_misc.so.0 => not found
    libidn.so.11 => not found
    libpam.so.0 => not found
    libpam_misc.so.0 => not found
    libidn.so.11 => not found
    libpam.so.0 => not found
    libpam_misc.so.0 => not found
    libpam.so.0 => not found
    libpam_misc.so.0 => not found
    libidn.so.11 => not found
    libpam.so.0 => not found
    libpam_misc.so.0 => not found

Thanks.

Kolar

**Comment by msmith626** [comment]
Looks like its linked against libpam and friends... we don't have a good way to add that into ESOS, and honestly don't have any interest in doing so. If its just temporary, you could try scp'ing those libraries from another installed Linux distro into /usr/lib and it should be fine.

--Marc
