### ISSUE TITLE
host initiator length too short

### ISSUE THREAD

**Issue by peter17919** [parodyne/esos#199]
I'm using vmware,the initior is : iqn.1998-01.com.vmware:58f64804-821d-486a-bf44-1866daf9b6ca-1918c4d1
but i can't  input from esos tui, the name is cutted by esos default length.
what should do ?

**Comment by feldsam** [comment]
Hi, try to use command line utility `scstadmin --help`

**Comment by peter17919** [comment]
got it ,tks,done.

**Comment by msmith626** [comment]
Was this actually an issue with the TUI, or was it just scrolling and
looked like it was cutting it off? I'll test shortly...

**Comment by msmith626** [comment]
Ah, yeah, indeed it does not all fit... current maximum length value is 64.
I'll increase it to 128.

diff --git a/tui/system.h b/tui/system.h
index 76365cb..7754182 100644
--- a/tui/system.h
+++ b/tui/system.h
@@ -232,7 +232,7 @@ extern "C" {
 #define MAX_SCST_DEV_NAME_LEN       SCST_DEV_NAME_LEN + 1
 #define SCST_SEC_GRP_NAME_LEN       16
 #define MAX_SCST_SEC_GRP_NAME_LEN   SCST_SEC_GRP_NAME_LEN + 1
-#define SCST_INITIATOR_LEN          64
+#define SCST_INITIATOR_LEN          128
 #define MAX_SCST_INITIATOR_LEN      SCST_INITIATOR_LEN + 1
 #define SCST_DEV_GRP_NAME_LEN       16
 #define MAX_SCST_DEV_GRP_NAME_LEN   SCST_DEV_GRP_NAME_LEN + 1

Strange that this has never come up before... are you using a new ESXi
version, 6.5 or something? Maybe the unique identifier is more bytes now?
Either way, I'll get this fixed, thanks for reporting.


--Marc

**Comment by peter17919** [comment]
yes,my esxi ver is 6.5.thx.

**Comment by msmith626** [comment]
I'll close this once I've applied the patch.

**Comment by msmith626** [comment]
This fix is included in master and the new 1.1.2 release (from 1.x.x).

--Marc
