### ISSUE TITLE
persist .ssh/authorized_keys

### ISSUE THREAD

**Issue by ModulaShop** [parodyne/esos#201]
Hello,
just starting to use esos as a zfs-backed storage for proxmox via a custom zfs-over-iscsi plugin. The way it works is the hypervisor configuring zfs and scst-targets via ssh. 

This makes use of ssh-copy-id to allow the hypvervisor running some commands on the array.

Unfortunately, the ssh-keys in /root/.ssh/authorized_keys are not persistent.

What would be the best approach keeping the keys over reboots ?
In 22_Advanced_System_Setup there is /etc/pre-scst_xtra_conf that is obviously called before scst is started. This would maybe work, but is clumsy, for sure.

/etc/rc.local would be my second guess

Thanks,
Alex

**Comment by msmith626** [comment]
Hi Alex,

I think the best bet would would be to do something like this:
- After you have already created /root/.ssh/authorized_keys copy the file
to /etc/
- Then as you said, in /etc/rc.local add something like this:
mkdir /root/.ssh
cp /etc/authorized_keys /root/.ssh/
chmod 600 /root/.ssh/authorized_keys

(Not sure if the permissions are correct above, but I think they need to be
something special, but maybe not.)


--Marc

**Comment by ModulaShop** [comment]
Hi Mark,
thanks, this is exactly what i was going to do, should be no problem to figure it out so that it works.

Just wondered if there was some other mechanism in place that would be better.

Alex

P.S.: Any chance you'd enable nfs-kernel-server in the kernel-config, maybe even by an option when building ? Would love to share a small part of my array by nfs to workstations directly.

**Comment by msmith626** [comment]
Possibly NFS in the future. For the time being you can build from source
and just enable that kernel option in the misc/linux-4.19.27.config file.

--Marc

**Comment by ModulaShop** [comment]
Hi Marc,
thanks, tried enabling NFS but didn't work at first try but then became short in time and can do without NFS atm. So, i put enabling NFS this in hold. 

Think you can close this issue.

Alex

**Comment by msmith626** [comment]
Okay, closing for now, but will likely enable NFS in the near future.

--Marc

**Comment by ModulaShop** [comment]
> Okay, closing for now, but will likely enable NFS in the near future.

Nice ! Just stumbled about the entry that original topic is solved and not about nfs.
