### ISSUE TITLE
VG <vg_name> init failed: invalid parameters for sanlock

### ISSUE THREAD

**Issue by axxana** [parodyne/esos#203]
Hi,
Sanlock and lvmlockd are running on my system.
When trying to create a shared VG (vgcreate --shared <vg_name> /dev/sdb1 /dev/sdc1) I receive the following errors
_VG <vg_name> init failed: invalid parameters for sanlock.
Failed to initialize lock args for lock type sanlock_

What are the invalid parameters? How should they be sent?

Please advise.

Thanks.

**Comment by msmith626** [comment]
Can you get any more information by adding a '--verbose' flag? Please share
your /etc/lvm/lvm.conf file and any parameters used when starting sanlock.

--Marc

**Comment by msmith626** [comment]
Also any relevant log lines in /var/log/ (perhaps /var/log/sanlock.log if
it is generated).

**Comment by axxana** [comment]
VGCREATE with --verbose

No PV label found on /dev/vglock/locklv.
No PV label found on /dev/sda1.
No PV label found on /dev/sda5.
Enabling sanlock global lock
Wiping internal VG cache
Wiping cache of LVM-capable devices
Wiping signatures on new PV /dev/sdb1.
Wiping signatures on new PV /dev/sdc1.
Adding physical volume '/dev/sdb1' to volume group 'vg1'
Adding physical volume '/dev/sdc1' to volume group 'vg1'
Archiving volume group "vg1" metadata (seqno 0).
Creating logical volume lvmlock
Creating volume group backup "/etc/lvm/backup/vg1" (seqno 2).
Activating logical volume vg1/lvmlock locally.
activation/volume_list configuration setting not defined: Checking only host tags for vg1/lvmlock.
Creating vg1-lvmlock
Loading vg1-lvmlock table (252:1)
Resuming vg1-lvmlock (252:1)
Initializing 4.00 KiB of logical volume "vg1/lvmlock" with value 0.
Logical volume "lvmlock" created.
VG vg1 init failed: invalid parameters for sanlock
Removing vg1-lvmlock (252:1)
Failed to initialize lock args for lock type sanlock
Removing physical volume "/dev/sdb1" from volume group "vg1"
Removing physical volume "/dev/sdc1" from volume group "vg1"
Volume group "vg1" successfully removed

**Comment by axxana** [comment]
/var/log/sanlock.log

2017-09-29 20:24:25 179338 [5835]: sanlock daemon started 3.5.0 host b8d64a1d-e3d3-44d7-985a-949bd1266d13.ubuntu16-1
2017-09-29 20:24:32 179344 [5845]: open error -13 /dev/mapper/vg1-lvmlock

**Comment by axxana** [comment]
[lvm.conf.log](https://github.com/parodyne/esos/files/1345162/lvm.conf.log)

**Comment by axxana** [comment]
I also added the LV to activation/volume_list
_activation/volume_list configuration setting defined: Checking the list to match vg1/lvmlock._
but still get the error
_VG vg1 init failed: invalid parameters for sanlock
Removing vg1-lvmlock (252:1)
Failed to initialize lock args for lock type sanlock_
What are the "**valid** parameters"?

Thanks.

**Comment by msmith626** [comment]
Does the 'lock_type' parameter need to be updated? Is lvmlockd running? Have you read the man page for lvmlockd yet -- it talks quite a bit about sanlock and needing a special VG for it... maybe that's what you're trying to create now. There is currently a GH issue open for adding sanlock support.

--Marc

**Comment by axxana** [comment]
I get the same error with or without --lock-type.
I read the manual. Here's my script. Any comments?

#Create the lock VG
vgcreate ff --config global/use_lvmlockd=0 vglock /dev/sdb2
lvcreate -n locklv -L 10MB vglock
systemctl start sanlock
lvmlockd -g sanlock --host-id 1
systemctl status sanlock
sanlock direct init -s lsgl:1:/dev/vglock/locklv:0

#Craete the shared VG
pvcreate -ff --config global/use_lvmlockd=0 /dev/sdb1 /dev/sdc1
vgcreate --verbose --shared vg1 /dev/sdb1 /dev/sdc1 --lock-type sanlock

Thanks a lot.

**Comment by msmith626** [comment]
Huh, systemctl? You're not using ESOS? In either case, I'd go to the
linux-lvm mailing list and inquire on usage. We haven't added support for
sanlock to ESOS yet, and haven't QA'd it even on a different Linux distro
yet.

--Marc

**Comment by axxana** [comment]
Will do, thanks a lot!

**Comment by axxana** [comment]
Do you have an estimation when the support for sanlock in ESOS will be released?

**Comment by msmith626** [comment]
I'm curious... why and how would use sanlock in a dual-head ESOS array
(cluster) vs. the standard/supported methods (the Linux cluster stack)? It
is something we'd like to add support for eventually... it's worth
mentioning that Parodyne customers do get preference for new ESOS features
if you're interested: https://www.parodyne.com/init/products/support

--Marc

**Comment by msmith626** [comment]
Issue #202 already exists for the sanlock enhancement request, so we'll close this one.
