### ISSUE TITLE
Error in the start script /etc/rc.d/rc.nut

### ISSUE THREAD

**Issue by 6ax** [parodyne/esos#206]
Hi,

When executing /etc/rc.d/rc.nut start 

Getting an error:

`Starting NUT UPS drivers...`
`/etc/rc.d/rc.nut: line 17: /usr/bin/upsdrvctl: No such file or directory`

The right path should be this:

	/usr/sbin/upsdrvctl

Tnx.

ESOS 1.3.4

**Comment by msmith626** [comment]
Thank you; we'll get this fix pushed in the next couple days:
diff --git a/etc/rc.d/rc.nut b/etc/rc.d/rc.nut
index cb6fe06..ce60f0e 100755
--- a/etc/rc.d/rc.nut
+++ b/etc/rc.d/rc.nut
@@ -4,7 +4,7 @@ source /etc/rc.d/common
 
 UPSD="/usr/sbin/upsd"
 UPSMON="/usr/sbin/upsmon"
-UPSDRVCTL="/usr/bin/upsdrvctl"
+UPSDRVCTL="/usr/sbin/upsdrvctl"
 UPSD_LOCK="/var/lock/upsd"
 UPSMON_LOCK="/var/lock/upsmon"
 UPSDRVCTL_LOCK="/var/lock/upsdrvctl"

Other than that rc script change, NUT is working as expected? Thanks for reporting this.

--Marc

**Comment by 6ax** [comment]
Yes, binaries work as expected, but the initialization script is far from perfect. The script will not let the daemon run in client mode, only as server and client together. I think it would be better to have two separate scripts for the server and client mode. To work in client mode, I wrote a script:

/etc/rc.d/rc.nut-client

#! /bin/sh

source /etc/rc.d/common

UPSMON="/usr/sbin/upsmon"
UPSMON_LOCK="/var/lock/upsmon"
NUT_USER="nutmon"
NUT_GROUP="nut"

check_args ${@}

start() {
    /bin/echo "Starting NUT UPS monitor..."
    /bin/mkdir -p /var/state/ups/upssched/ &&
    /bin/chown ${NUT_USER}:${NUT_GROUP} /usr/sbin/upssched /usr/bin/upssched-cmd /var/state/ups/upssched &&
    ${UPSMON} -u ${NUT_USER} || exit 1
    /bin/touch ${UPSMON_LOCK} 
}

stop() {
    /bin/echo "Stopping NUT UPS monitor..."
    ${UPSMON} -c stop && /bin/rm -f ${UPSMON_LOCK} 
}

status() {
    /bin/pidof ${UPSMON} > /dev/null 2>&1
    exit ${?}
}

${1}

I think that for the server mode the script will be easier =)

P.S
Sorry for my bad english.

**Comment by msmith626** [comment]
The original issue has been fixed in ESOS 1.3.5 and the new package should post later today. I created a separate issue (#209) for the recommendation of splitting rc.nut into two separate rc scripts. Thank you.
