### ISSUE TITLE
LSI FC LIP Permission Denied

### ISSUE THREAD

**Issue by michaelbroyles** [parodyne/esos#216]
No matter what I do I'm unable to get ESOS to issue a LIP for my LSI Fibre Channel cards. I get Permission Denied.

**Comment by msmith626** [comment]
An LSI Fibre Channel adapter with ESOS? A custom build? Need more information.

**Comment by msmith626** [comment]
Were you able to resolve this issue?

**Comment by bitcoins1g** [comment]
Having the same problem, also LSI FC card. Links fine with the FC Switch, gets data from /sys/class/fc_host

**Comment by msmith626** [comment]
Which target driver are you using? Please share your /etc/scst.conf file.

--Marc

**Comment by msmith626** [comment]
No response, closing...
