### ISSUE TITLE
pvcreate freezes on "Wiping internal VG cache"

### ISSUE THREAD

**Issue by Aleksey-Maksimov** [parodyne/esos#217]
Hello.

I have a software RAID /dev/md0 in ESOS 1.3.6
If md0 is present in SCST as a single device (aka LUN 0 via iSCSI), then everything works.
But I need to make two LUNs on the md0 disk.
In TUI, the call to the "Add Physical Volume (PV)" command causes the TUI to hang.
I try to create LVM PV manually:

```
# pvcreate --verbose /dev/md0

     Wiping internal VG cache
```

On this command hangs and nothing happens.
Nothing appears in the syslog.log and messages logs.

Tell me, please, what could be the problem.

**Comment by msmith626** [comment]
Hmm... can you clear any LVM cache files in /etc/lvm/cache (or maybe it's
.cache) and see if that helps?

**Comment by msmith626** [comment]
Any luck diagnosing this further?

**Comment by msmith626** [comment]
Were you able to resolve this issue?

**Comment by Aleksey-Maksimov** [comment]
Hello Marc.
Sorry that I did not respond quickly.
Clearing the LVM cache did not help. The problem was reproduced on two servers, where I tried to do this. Then I abandoned the idea of using LVM in ESOS. 
Thanks for your reply.
