### ISSUE TITLE
RAM-Disk as target device

### ISSUE THREAD

**Issue by Aleksey-Maksimov** [parodyne/esos#220]
Hello,

Is there any possibility of using a RAM disk as the target ESOS device?

**Comment by msmith626** [comment]
No persistent RAM disk exists in ESOS currently, although you could
probably use something like a tmpfs file system with "virtual disk
files". If you know of a good project that is a persistent RAM disk
(or otherwise), please let us know and we can look at including this
in ESOS.

--Marc

**Comment by Aleksey-Maksimov** [comment]
Maybe we can somehow mount part of the memory as a tmpfs-disk as a file and give it to SCST via vdisk_fileio? What do you think of it? Can this be done?

**Comment by msmith626** [comment]
Yes, that could probably be done... add an entry in /etc/fstab and make the
mount point in "/mnt/vdisks/mount_point" and that *should* work.

--Marc

**Comment by Aleksey-Maksimov** [comment]
Thanks, Marc
