### ISSUE TITLE
Minor issue: On main screen, link speed "N/A" for targets that start with "0" (zero) 

### ISSUE THREAD

**Issue by mastergregor** [parodyne/esos#221]
I have installed the 1.3.9 on Dell FS12-TY (C2100) and I noticed that link speed for a target that starts with zero is N/A. The same target/link otherwise works fine, it can process traffic and works as expected with initiators. QLE2564 card, PERC H700, released vanilla build with PERC tools added. 

I looked briefly into this, with my limited knowledge of ESOS, and it appears all the info (correct speed as well) is present in /sys/class/fc_host/ location for each host, so this is possibly a parsing error of some sort, with leading zero messing up a string somewhere. This is just a guess though.

In my particular case, from the location of interest:

> [root@storagecobra host8]# pwd
> /sys/class/fc_host/host8
> [root@storagecobra host8]# cat port_name
> 0x1b80024ff9517eb
> [root@storagecobra host8]# cat port_id
> 0x0000e8
> [root@storagecobra host8]# cat port_state
> Online
> [root@storagecobra host8]# cat speed
> 8 Gbit
> [root@storagecobra host8]# cat node_name
> 0xb80024ff9517eb
> [root@storagecobra host8]# cat symbolic_name
> QLE2564 FW:v7.03.00 DVR:v8.04.00.05.2.2-SCST.03-k-p

I am attaching a pic of TUI wich illustrates the issue.

![capture](https://user-images.githubusercontent.com/43911786/46573272-917d1980-c958-11e8-9c13-028ba9fc1a89.PNG)

Let me know how I can help out.

Thanks,
Gregor

**Comment by msmith626** [comment]
Thank you for reporting this. As you mentioned, it appears the sysfs
attribute in the fc_class subdirectory is missing the leading '0' of
the WWPN for this HBA, so it fails to match the SCST target name
value. Here is the relevant section of code that grabs the speed
attribute value from the fc_host structure:

--snip--
    /* Fibre Channel / FCoE adapter information */
    if ((dir_stream = opendir(SYSFS_FC_HOST)) == NULL) {
        if (row_cnt < MAX_INFO_LABEL_ROWS) {
            snprintf(line_buffer, TARGETS_LABEL_COLS, "opendir(): %s",
                    strerror(errno));
            SAFE_ASPRINTF(&label_msg[row_cnt], "%s", line_buffer);
        }
        return row_cnt;
    }
    while ((dir_entry = readdir(dir_stream)) != NULL) {
        /* The hostX directory names are links */
        if (dir_entry->d_type == DT_LNK) {
            /* Get the port name */
            snprintf(attr_path, MAX_SYSFS_PATH_SIZE, "%s/%s/port_name",
                    SYSFS_FC_HOST, dir_entry->d_name);
            readAttribute(attr_path, attr_val);
            /* Make the port name match a SCST target name */
            temp_pstr = strchr(attr_val, 'x');
            if (temp_pstr != NULL) {
                temp_pstr++;
                while ((temp_int = strlen(temp_pstr)) != 0) {
                    if (!((temp_int - 2) < 0)) {
                        if (port_name_size >= MAX_SYSFS_ATTR_SIZE) {
                            break;
                        } else {
                            strncat(fc_port_name[fc_adp_cnt], temp_pstr, 2);
                            port_name_size = port_name_size + 2;
                            if ((temp_int - 2) != 0) {
                                strncat(fc_port_name[fc_adp_cnt], ":", 1);
                                port_name_size++;
                            }
                            temp_pstr = temp_pstr + 2;
                        }
                    } else {
                        break;
                    }
                }
            }
            /* Get speed string */
            snprintf(attr_path, MAX_SYSFS_PATH_SIZE, "%s/%s/speed",
                    SYSFS_FC_HOST, dir_entry->d_name);
            readAttribute(attr_path, attr_val);
            snprintf(fc_speed[fc_adp_cnt], MAX_SYSFS_ATTR_SIZE, "%s", attr_val);
        }
        fc_adp_cnt++;
    }
    closedir(dir_stream);
--snip--

I'm open to feedback on a fix... we always know the number of
characters in the WWPN, and if it doesn't match, perhaps we can
blindly prefix the string with a '0' to force a match? Thoughts?

--Marc

**Comment by mastergregor** [comment]
Hm, looking at the code snippet, I am not sure how is speed not propagated correctly. The first part creates a WWPN with all the ":" in between, and starts to concatenate from "x" from the name. So if the name does not have a "0" right after the X, the WWPN should be off, since strncat does it in increments of 2. The same name is then used to get speed, so if one portion works, so should the second one? Maybe running this through a debugger would give me a better insight into this.

Now, looking into this a bit, I see that info_labels.c is of interest here, and in this file, a bit further down from the snippet you posted I found the following (line 338):

            if (strcmp(tgt_name[i], fc_port_name[j]) == 0) {
                /* Add speed/rate if its a matching FC adapter */
                snprintf(tgt_speed_str[i], MAX_SYSFS_ATTR_SIZE,
                        "%s", fc_speed[j]);
                break;
            }

Even further down is the check if speed was populated in tgt_speed_str, and if string is null, "N/A" is added (line 353). Maybe the previous check fails?

        
    if (tgt_speed_str[i][0] == '\0')
          snprintf(tgt_speed_str[i], MAX_SYSFS_ATTR_SIZE, "N/A");

It may be useful to run this through a debug session, to make sure we are looking at the right place for this problem. It will take me a while to set up debugging though.

Now, if I am just chasing a red herring here, then logical solution might be what you suggested Marc - check for the length of WWPN, and pad it on the front with "0"s. Would there be a similar issue with trailing "0"? I am not sure it is a problem, since ascii "0" is not the same as '\0', so it should be OK? 

Gregor

**Comment by msmith626** [comment]
Can you try the attached 'esos_tui' binary. Place it in /root then gunzip it, and run it manually: ./esos_tui
Let me know if this resolves it (or not). Here is the change:
diff --git a/tui/info_labels.c b/tui/info_labels.c
index 9010882..aeb1837 100644
--- a/tui/info_labels.c
+++ b/tui/info_labels.c
@@ -273,7 +273,13 @@ int readTargetData(char *label_msg[]) {
             /* Make the port name match a SCST target name */
             temp_pstr = strchr(attr_val, 'x');
             if (temp_pstr != NULL) {
-                temp_pstr++;
+                /* In sysfs, if the WWPN begins with a '0' then in the
+                 * port_name sysfs attribute, the leading '0' character is
+                 * truncated, fix this by changing the 'x' to a '0' */
+                if (strlen(temp_pstr) != 17)
+                    *temp_pstr = '0';
+                else
+                    temp_pstr++;
                 while ((temp_int = strlen(temp_pstr)) != 0) {
                     if (!((temp_int - 2) < 0)) {
                         if (port_name_size >= MAX_SYSFS_ATTR_SIZE) {

--Marc
[esos_tui.gz](https://github.com/parodyne/esos/files/2507964/esos_tui.gz)

**Comment by mastergregor** [comment]
Works as expected! Thank you for the new "feature" :)

I am attaching a picture of the TUI working.

![fixedspeed](https://user-images.githubusercontent.com/43911786/47402045-537a4680-d709-11e8-86e5-aec40b952afb.PNG)

**Comment by msmith626** [comment]
Great, thanks for confirming this. I'll push this up in the next day or two
and it will be in a new release of ESOS as well.

--Marc

**Comment by msmith626** [comment]
This fix has been included in the master and 1.x.x branches... the new release 1.3.10 will post in a few hours to the downloads area.

--Marc

**Comment by cosminidis** [comment]
Hi guys, the same happens in 4.0.12 for iSCSI:

[root@esos1-srv net]# cat eno1/address
08:f1:ea:e1:6b:20

![image](https://user-images.githubusercontent.com/44065909/197580791-444efbe2-a452-4b1a-ad53-d7a186592ae5.png)
