### ISSUE TITLE
Migrate Open-E FC Targets

### ISSUE THREAD

**Issue by briansumma** [parodyne/esos#222]
Is it possible to Migrate Open-E Fibre Channel BLOCKIO Targets (also based on SCST and LVM) to ESOS?

**Comment by msmith626** [comment]
I don't see why not. It would of course be a disruptive
migration/transition, but you should be able to boot ESOS on the same
hardware and produce a similar configuration. Especially if you have the
scst.conf file from the Open-E machine. Do you know which version of SCST
Open-E uses in the release you're running?

--Marc

**Comment by msmith626** [comment]
No, I wouldn't expect it to be destructive as long as the SCST
configuration is the same (eg, keep exact same device name so EUI stays the
same, and especially make sure the logical block size... blocksize
attribute... is the same).

But yes, I'd have a good solid backup just in case. I have upgraded ESOS
machines from a long time ago that used SCST 2.x to newer versions of ESOS
which use SCST 3.x without issue.

--Marc
