### ISSUE TITLE
Color schems in TUI

### ISSUE THREAD

**Issue by GoogleCodeExporter** [parodyne/esos#51]
```
There should be a config point in TUI for changing the colortheme live.



```

Original issue reported on code.google.com by `mahir.ya...@gmail.com` on 22 Feb 2014 at 10:04

**Comment by mahiryaylacioglu** [comment]
Hi Marc,

can you at least change text color to yellow by now?

grey text on green background is very hard to read...

**Comment by msmith626** [comment]
I've actually already started work on this request, on my machine along
with a number of other TUI enhancements, but its not ready to be pushed to
GitHub yet... hopefully in the next couple weeks. But for now, yes, white
(grey maybe on console) on blue / aqua is all there is for now. I have
noticed viewing the TUI in a terminal emulator (eg, via SSH) is much easier
to read then the physical console.

--Marc

**Comment by msmith626** [comment]
Finally, this has been implemented (master branch). Just one other color theme for now (two total), but we can easily add more in the future.

--Marc
