### ISSUE TITLE
more configuration possibilities in TUI for scst

### ISSUE THREAD

**Issue by GoogleCodeExporter** [parodyne/esos#53]
```
it would be nice if in the TUI things like HeaderDiggest and DataDiggest could 
be configurable.
```

Original issue reported on code.google.com by `mahir.ya...@gmail.com` on 22 Feb 2014 at 10:07

**Comment by msmith626** [comment]
We've decided not to implement this enhancement; users wishing to modify advanced SCST configuration options can edit /etc/scst.conf directly, or use the scstadmin tool to change attributes.
