### ISSUE TITLE
Feature Request. from address at mail configuration

### ISSUE THREAD

**Issue by GoogleCodeExporter** [parodyne/esos#96]
```
My email server enforces that, from address and smtp auth user be the same.
Could you please include from field at email config?

JL
```

Original issue reported on code.google.com by `javier.l...@gmail.com` on 23 Mar 2015 at 1:09

**Comment by msmith626** [comment]
We have decided to not implement this enhancement. Users that would like a different "from" address in the emails can modify the sSMTP configuration directly.

**Comment by singlecheeze** [comment]
@msmith626 I know this is an old thread, but figured I'd post anyway.

I ran into this tonight after setting up ESOS for the first time tonight, and was successfully able to setup gmail to work, but the docs need a quick update to note that Google now requires:
https://support.google.com/a/answer/176600?hl=en#zippy=%2Cuse-the-gmail-smtp-server

- Less secure apps turned on in gmail account
- 2FA on the account
- An "App Password" generated (Default gmail password will not work)

After that, the test email worked like a charm!

**Comment by singlecheeze** [comment]
@msmith626 good to know, but how would it be modified?

I looked at the C++ tonight but it's unclear what would need to be added to: /etc/ssmtp/ssmtp.conf
